/*
 * Copyright (C) 2025 Quasient Inc. <https://www.quasient.com>
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in the file LICENSE and at https://mariadb.com/bsl11
 *
 * Change Date: 2029-10-01
 * Change License: Apache 2.0
 */
package com.quasient.pal.core.dispatcher;

import com.quasient.pal.core.execution.java.ClassMethodDispatcher;
import com.quasient.pal.core.execution.java.ConstructorDispatcher;
import com.quasient.pal.core.execution.java.GetClassVariableDispatcher;
import com.quasient.pal.core.execution.java.GetInstanceVariableDispatcher;
import com.quasient.pal.core.execution.java.InstanceMethodDispatcher;
import com.quasient.pal.core.execution.java.SetClassVariableDispatcher;
import com.quasient.pal.core.execution.java.SetInstanceVariableDispatcher;
import com.quasient.pal.core.intercept.IncomingInterceptCallbackDispatcher;
import com.quasient.pal.core.transport.MessageChannelType;
import com.quasient.pal.messages.colfer.ControlMessage;
import com.quasient.pal.messages.colfer.ExecMessage;
import com.quasient.pal.messages.colfer.InterceptCallbackRequestMessage;
import com.quasient.pal.messages.colfer.InterceptCallbackResponseMessage;
import com.quasient.pal.messages.colfer.MetaMessage;
import com.quasient.pal.messages.types.MessageType;
import com.quasient.pal.serdes.colfer.ColferUtils;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Routes incoming messages to their appropriate dispatcher components.
 *
 * <p>This class uses dependency injection to obtain various dispatchers responsible for handling
 * different types of messages, such as execution (exec), control, and meta messages. Depending on
 * the message type provided, the corresponding dispatcher is invoked to perform the necessary
 * operation, including method invocations, field access, or object construction.
 */
@Singleton
public class IncomingMessageDispatcher {

  /** Logger instance. */
  protected static final Logger logger = LoggerFactory.getLogger(IncomingMessageDispatcher.class);

  // constructor & method dispatchers

  /** Dispatcher that handles messages invoking constructor operations. */
  @SuppressWarnings("unused")
  @Inject
  private ConstructorDispatcher constructorDispatcher;

  /** Dispatcher that handles messages invoking static class methods. */
  @SuppressWarnings("unused")
  @Inject
  private ClassMethodDispatcher classMethodDispatcher;

  /** Dispatcher that handles messages invoking instance methods. */
  @SuppressWarnings("unused")
  @Inject
  private InstanceMethodDispatcher instanceMethodDispatcher;

  // field op dispatchers

  /** Dispatcher that handles retrieval of static field values. */
  @SuppressWarnings("unused")
  @Inject
  private GetClassVariableDispatcher getClassVariableDispatcher;

  /** Dispatcher that handles assignment to static fields. */
  @SuppressWarnings("unused")
  @Inject
  private SetClassVariableDispatcher setClassVariableDispatcher;

  /** Dispatcher that handles retrieval of instance field values. */
  @SuppressWarnings("unused")
  @Inject
  private GetInstanceVariableDispatcher getInstanceVariableDispatcher;

  /** Dispatcher that handles assignment to instance fields. */
  @SuppressWarnings("unused")
  @Inject
  private SetInstanceVariableDispatcher setInstanceVariableDispatcher;

  // control message dispatcher

  /** Dispatcher that processes control messages used for runtime management. */
  @SuppressWarnings("unused")
  @Inject
  private ControlMessageDispatcher controlMessageDispatcher;

  // meta message dispatcher

  /** Dispatcher that processes meta messages related to system metadata operations. */
  @SuppressWarnings("unused")
  @Inject
  private MetaMessageDispatcher metaMessageDispatcher;

  // intercept callback dispatcher

  /** Dispatcher that processes intercept callback requests from intercepted peers. */
  @SuppressWarnings("unused")
  @Inject
  private IncomingInterceptCallbackDispatcher incomingInterceptCallbackDispatcher;

  /**
   * Dispatches an execution message to its appropriate handler based on the specified message type.
   *
   * <p>This method examines the provided {@code messageType} and delegates the processing of the
   * associated {@code execMessage} to the corresponding dispatcher. The {@link MessageChannelType}
   * parameter indicates the source transport channel where the message was received.
   *
   * @param execMessage the execution message containing invocation details
   * @param messageType the type of execution message that determines which dispatcher to invoke
   * @param messageChannelType the transport channel through which the message was received
   * @return the response execution message generated by the appropriate dispatcher
   * @throws UnsupportedMessageException if the provided message type does not map to any supported
   *     dispatcher
   */
  public ExecMessage incomingCall(
      ExecMessage execMessage, MessageType messageType, MessageChannelType messageChannelType) {

    return switch (messageType) {
      case EXEC_CONSTRUCTOR ->
          constructorDispatcher.dispatchIncoming(execMessage, messageChannelType);
      case EXEC_INSTANCE_METHOD ->
          instanceMethodDispatcher.dispatchIncoming(execMessage, messageChannelType);
      case EXEC_CLASS_METHOD ->
          classMethodDispatcher.dispatchIncoming(execMessage, messageChannelType);
      case EXEC_GET_STATIC ->
          getClassVariableDispatcher.dispatchIncoming(execMessage, messageChannelType);
      case EXEC_GET_FIELD ->
          getInstanceVariableDispatcher.dispatchIncoming(execMessage, messageChannelType);
      case EXEC_PUT_STATIC ->
          setClassVariableDispatcher.dispatchIncoming(execMessage, messageChannelType);
      case EXEC_PUT_FIELD ->
          setInstanceVariableDispatcher.dispatchIncoming(execMessage, messageChannelType);
      default ->
          throw new UnsupportedMessageException(
              String.format(
                  "Incoming exec message ignored - no handler:%n%s",
                  ColferUtils.format(execMessage)));
    };
  }

  /**
   * Delegates the provided control message to the control message dispatcher for processing.
   *
   * @param controlMessage the control message to be processed
   * @return the control message response after being handled by the dispatcher
   */
  public ControlMessage incomingControlMessage(ControlMessage controlMessage) {
    return controlMessageDispatcher.incomingControlMessage(controlMessage);
  }

  /**
   * Delegates the provided meta message to the meta message dispatcher for processing.
   *
   * @param metaMessage the meta message to be processed
   * @return the meta message response after being handled by the dispatcher
   */
  public MetaMessage incomingMetaMessage(MetaMessage metaMessage) {
    return metaMessageDispatcher.incomingMetaMessage(metaMessage);
  }

  /**
   * Delegates the provided intercept callback request to the intercept callback dispatcher for
   * processing.
   *
   * <p>This method is invoked when an intercepted peer sends a callback request to this peer. The
   * dispatcher will resolve the callback handler, invoke it with an {@link
   * com.quasient.pal.common.lang.intercept.InterceptContext}, and return a response.
   *
   * @param callbackRequest the intercept callback request to be processed
   * @return the intercept callback response after being handled by the callback
   */
  public InterceptCallbackResponseMessage incomingInterceptCallback(
      InterceptCallbackRequestMessage callbackRequest) {
    return incomingInterceptCallbackDispatcher.handleCallback(callbackRequest);
  }
}
