/*
 * Copyright (C) 2026 Quasient Inc. <https://www.quasient.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quasient.foobar.apps.quantized.execution;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.function.BiFunction;
import java.util.function.Function;

/**
 * Test application that exercises the supplementary {@code execution()} pointcuts woven into {@code
 * FullQuantizeAspect}.
 *
 * <p>Each path invokes a distinct target method so integration tests can assert the presence or
 * absence of specific method names in the recorded WAL:
 *
 * <ol>
 *   <li>{@link #normalMethod(String)} — invoked via a direct, woven-to-woven call. Used to verify
 *       that the thread-local guard suppresses double-dispatch (exactly one WAL entry per
 *       invocation).
 *   <li>{@link #reflectedInstanceMethod(String)} — invoked via {@link Method#invoke(Object,
 *       Object...)} on an instance. The call site is unwoven (inside {@code java.lang.reflect});
 *       the method body must be captured by execution-site advice.
 *   <li>{@link #methodReferenceTarget(String)} — invoked through a <strong>bound</strong> method
 *       reference ({@code app::methodReferenceTarget}) stored in a {@link Function}. The {@code
 *       invokedynamic}/{@code LambdaMetafactory} call site is not a direct call; execution-site
 *       advice on the target body captures it.
 *   <li>{@link #unboundRefTarget(String)} — invoked through an <strong>unbound</strong> method
 *       reference ({@code ExecutionPointcutApp::unboundRefTarget}) stored in a {@link BiFunction}
 *       that receives the instance as its first argument at each call.
 *   <li>{@link #staticRefTarget(String)} — invoked through a <strong>static</strong> method
 *       reference ({@code ExecutionPointcutApp::staticRefTarget}) stored in a {@link Function}.
 *   <li>{@link #reflectedStaticMethod(String)} — static method invoked via {@link
 *       Method#invoke(Object, Object...)} with a {@code null} receiver.
 *   <li>{@link #lambdaTarget(String)} — invoked from inside a lambda body. Verifies that regardless
 *       of lambda metafactory/JIT shape, execution-site advice on the callee captures the call.
 *   <li>{@link #ExecutionPointcutApp(String)} — invoked via {@link
 *       Constructor#newInstance(Object...)}. The reflective instantiation bypasses call-site
 *       constructor weaving; execution-site constructor advice on the body captures it.
 *   <li>{@link #recursiveCount(int)} — directly recursive instance method. Verifies that the
 *       call-site/execution-site guard keys still agree for each frame of a self-recursion, so the
 *       WAL contains exactly one OPERATION entry per recursion level, not two.
 *   <li>{@link #reflectiveRecursiveCount(int)} — recursive instance method whose nested call goes
 *       through {@link Method#invoke(Object, Object...)} rather than a direct call. Verifies that
 *       the execution-site advice clears the thread-local guard during the outer body's proceed, so
 *       an unwoven re-entry into the same method while the outer dispatch is still in flight is
 *       captured by the inner execution-site rather than silently suppressed.
 *   <li>{@link #lambdaRecursiveCount(int)} — recursive instance method whose nested call goes
 *       through a bound {@link Function} method reference held as a field. The synthetic {@code
 *       Function} implementation generated by {@code LambdaMetafactory} is unwoven, so re-entry
 *       into the target method bypasses call-site advice. Stands in for the most common real-world
 *       shape: a delegate field captured in the constructor and invoked from the same method's
 *       body.
 *   <li>{@link #methodHandleRecursiveCount(int)} — recursive instance method whose nested call goes
 *       through a {@link MethodHandle#invokeExact}. The {@code java.lang.invoke} dispatch path is
 *       unwoven and structurally distinct from {@link Method#invoke}; verifying it independently
 *       catches any future change that, for example, special-cases reflection but not method
 *       handles.
 *   <li>{@link #staticReflectiveRecursiveCount(int)} — recursive <em>static</em> method whose
 *       nested call goes through {@link Method#invoke(Object, Object...)} with a {@code null}
 *       receiver. Exercises {@code aroundVoid/NonVoidClassMethodsExec} on the recursion path, which
 *       is a different advice method than the instance variants.
 *   <li>{@link #mutualReflectiveCountA(int)} / {@link #mutualReflectiveCountB(int)} — mutual
 *       recursion via {@link Method#invoke}: A invokes B reflectively, B invokes A reflectively,
 *       alternating until {@code n == 0}. This is the load-bearing case for the fix: the outer
 *       dispatch chain holds A's key in the thread-local while B's body re-enters A through an
 *       unwoven layer. A bug that only cleared the slot when the recursion target equals the
 *       current method (rather than for every body proceed) would silently suppress the inner A
 *       invocation, leaving the WAL short by one entry per mutual cycle.
 *   <li>{@link VirtualBase#virtualMethod(String)} overridden by {@link
 *       VirtualSub#virtualMethod(String)}, invoked through the base-typed reference. The call-site
 *       sees {@code VirtualBase} statically but the runtime receiver is a {@code VirtualSub}. The
 *       guard key must use the runtime receiver class so call-site and execution-site agree —
 *       otherwise virtual dispatch would produce two WAL entries per call.
 *   <li>{@link VirtualIface#ifaceMethod(String)} implemented by {@link VirtualIfaceImpl}, invoked
 *       through the interface-typed reference. Same concern as virtual dispatch with an additional
 *       wrinkle: the call-site's declaring type is the interface while the execution-site runs on
 *       the concrete impl. The runtime-class-keyed guard must align both sides.
 *   <li>{@link #frameworkCallbackTarget(String)} — invoked from a {@link Runnable} dispatched by
 *       {@link Thread#start()}. The native {@code Thread.run()} bridge into the {@code Runnable}
 *       body is not a woven call-site, so the target method is only captured by execution-site
 *       advice. Stands in for framework-driven callbacks (Quarkus scheduler, JavaFX event dispatch,
 *       Spring MVC handler) where the caller is external/unwoven.
 * </ol>
 *
 * <p>The app prints a single-line {@code results: ...} marker that encodes each path's return
 * value, so recording / replay tests can assert deterministic output.
 */
public class ExecutionPointcutApp {

  /** Marker string assigned by a constructor; used to verify constructor reflection captured. */
  private String marker;

  /** Captures the return value of {@link #frameworkCallbackTarget(String)} across thread join. */
  private String frameworkCallbackResult;

  /**
   * Bound {@link Function} method reference to {@link #lambdaRecursiveCount(int)}, used to drive
   * the lambda-style recursion path. Held as a field so the body can re-enter the same method via
   * the unwoven {@code Function::apply} synthetic bridge generated by {@code LambdaMetafactory}.
   */
  private final Function<Integer, Integer> lambdaRecursiveRef = this::lambdaRecursiveCount;

  /**
   * {@link MethodHandle} resolved against {@link #methodHandleRecursiveCount(int)}, used to drive
   * the method-handle recursion path. Resolved once in a static initializer; the recursive call
   * re-enters the method via {@link MethodHandle#invokeExact(Object...)} rather than direct
   * dispatch. Throws {@link ExceptionInInitializerError} if the lookup fails — a fail-fast posture
   * appropriate for a test fixture.
   */
  private static final MethodHandle MH_RECURSIVE_COUNT;

  static {
    try {
      MH_RECURSIVE_COUNT =
          MethodHandles.lookup()
              .findVirtual(
                  ExecutionPointcutApp.class,
                  "methodHandleRecursiveCount",
                  MethodType.methodType(int.class, int.class));
    } catch (ReflectiveOperationException e) {
      throw new ExceptionInInitializerError(e);
    }
  }

  /**
   * Default no-arg constructor used for the app instance created in {@link #main(String[])}.
   *
   * <p>This constructor is invoked via a normal {@code new} expression (call-site weaving). The
   * {@link #ExecutionPointcutApp(String)} overload is invoked via reflection in the constructor
   * reflection path.
   */
  public ExecutionPointcutApp() {
    this.marker = "default";
  }

  /**
   * Constructor invoked via {@link Constructor#newInstance(Object...)} in the reflective
   * construction path.
   *
   * @param marker an arbitrary string stored on the instance and returned via {@link #getMarker()}
   */
  public ExecutionPointcutApp(String marker) {
    this.marker = marker;
  }

  /**
   * Returns the marker string assigned by the invoked constructor.
   *
   * @return the marker string
   */
  public String getMarker() {
    return marker;
  }

  /**
   * Target for the direct, woven-to-woven call path. Used to verify no double-dispatch.
   *
   * @param input the input string
   * @return {@code "n:" + input}
   */
  public String normalMethod(String input) {
    return "n:" + input;
  }

  /**
   * Target for the instance-method reflection path. Invoked via {@link Method#invoke(Object,
   * Object...)}.
   *
   * @param input the input string
   * @return {@code "r:" + input}
   */
  public String reflectedInstanceMethod(String input) {
    return "r:" + input;
  }

  /**
   * Target for the <strong>bound</strong> method-reference path. Invoked via a {@link Function}
   * constructed from {@code app::methodReferenceTarget} (the receiver is captured at the time the
   * reference is built).
   *
   * @param input the input string
   * @return {@code "mr:" + input}
   */
  public String methodReferenceTarget(String input) {
    return "mr:" + input;
  }

  /**
   * Target for the <strong>unbound</strong> method-reference path. Invoked via a {@link
   * java.util.function.BiFunction} constructed from {@code ExecutionPointcutApp::unboundRefTarget}
   * — the method reference takes the receiver as its first parameter at each call, so the call site
   * at {@code apply} is in a runtime-generated {@code BiFunction} implementation that is not woven.
   * Only execution-site advice on this method captures the invocation.
   *
   * @param input the input string
   * @return {@code "ur:" + input}
   */
  public String unboundRefTarget(String input) {
    return "ur:" + input;
  }

  /**
   * Target for the <strong>static</strong> method-reference path. Invoked via a {@link Function}
   * constructed from {@code ExecutionPointcutApp::staticRefTarget}. The static method reference is
   * dispatched from a runtime-generated {@link Function} implementation that is not woven — only
   * execution-site advice on this method captures the invocation.
   *
   * @param input the input string
   * @return {@code "sr:" + input}
   */
  public static String staticRefTarget(String input) {
    return "sr:" + input;
  }

  /**
   * Target for the lambda-captured-call path. Invoked from inside a lambda body.
   *
   * @param input the input string
   * @return {@code "l:" + input}
   */
  public String lambdaTarget(String input) {
    return "l:" + input;
  }

  /**
   * Target for the framework-style callback path. Invoked from a {@link Runnable} dispatched by
   * {@link Thread#start()} — a JDK-native entry point that stands in for framework callbacks (for
   * example, a Quarkus scheduler firing a scheduled method, JavaFX's event-dispatch thread calling
   * a handler, or Spring MVC dispatching a controller method). The bridge from {@code Thread.run()}
   * into the application-level callback body is not a woven call site, so only execution-site
   * advice on this method can capture the invocation.
   *
   * <p>The returned value is stored on the enclosing app instance via {@link
   * #frameworkCallbackResult} so that {@link #main(String[])} can read it after the thread joins.
   *
   * @param input the input string
   * @return {@code "fc:" + input}
   */
  public String frameworkCallbackTarget(String input) {
    return "fc:" + input;
  }

  /**
   * Target for the static-reflection path. Invoked via {@link Method#invoke(Object, Object...)}
   * with a {@code null} receiver.
   *
   * @param input the input string
   * @return {@code "s:" + input}
   */
  public static String reflectedStaticMethod(String input) {
    return "s:" + input;
  }

  /**
   * Directly recursive instance method used to verify that the thread-local guard correctly pairs
   * call-site and execution-site keys at every recursion depth.
   *
   * <p>For an input of {@code n}, the method is invoked {@code n + 1} times (depths {@code n}
   * through {@code 0}). The WAL should therefore contain exactly {@code n + 1} OPERATION entries
   * for this method — not {@code 2 * (n + 1)}, which would indicate the exec-site advice
   * double-dispatched at every frame.
   *
   * @param n the recursion depth (non-negative)
   * @return the number of nested calls made (equal to {@code n})
   */
  public int recursiveCount(int n) {
    if (n <= 0) {
      return 0;
    }
    return 1 + recursiveCount(n - 1);
  }

  /**
   * Recursive instance method whose nested call goes through {@link Method#invoke(Object,
   * Object...)} rather than a direct woven call. Verifies that an unwoven re-entry into the same
   * method from inside the body — while the outer dispatch is still in flight — is captured by its
   * own execution-site advice.
   *
   * <p>The outer invocation is dispatched by the call-site advice (which sets the thread-local
   * guard to this method's key). Inside the body, {@code Method.invoke} is unwoven and does not
   * fire the call-site advice, so the inner re-entry can only be captured by execution-site advice.
   * For that to happen the slot must be cleared during the outer body's {@code proceed}, otherwise
   * the inner exec-site sees a matching key and silently suppresses dispatch.
   *
   * <p>The WAL must contain exactly {@code n + 1} OPERATION entries for this method; anything less
   * indicates that one or more reflective frames were suppressed.
   *
   * @param n the recursion depth (non-negative)
   * @return the number of nested calls made (equal to {@code n})
   * @throws ReflectiveOperationException if the reflective lookup or invocation fails
   */
  public int reflectiveRecursiveCount(int n) throws ReflectiveOperationException {
    if (n <= 0) {
      return 0;
    }
    Method m = ExecutionPointcutApp.class.getMethod("reflectiveRecursiveCount", int.class);
    return 1 + (int) m.invoke(this, n - 1);
  }

  /**
   * Recursive instance method whose nested call goes through a bound {@link Function} method
   * reference held as a field, exercising the lambda / {@code LambdaMetafactory} re-entry path.
   *
   * <p>The synthetic class {@code LambdaMetafactory} generates to implement {@link Function} is
   * unwoven, so a call through {@link Function#apply(Object)} bypasses call-site advice on the
   * target. The inner re-entry into this method must be captured by execution-site advice; that
   * only happens if the slot is cleared during the outer body's proceed.
   *
   * <p>The WAL must contain exactly {@code n + 1} OPERATION entries for this method.
   *
   * @param n the recursion depth (non-negative)
   * @return the number of nested calls made (equal to {@code n})
   */
  public int lambdaRecursiveCount(int n) {
    if (n <= 0) {
      return 0;
    }
    return 1 + lambdaRecursiveRef.apply(n - 1);
  }

  /**
   * Recursive instance method whose nested call goes through {@link MethodHandle#invokeExact}
   * rather than {@link Method#invoke} or a direct call, exercising the {@code java.lang.invoke}
   * re-entry path.
   *
   * <p>{@code java.lang.invoke} is unwoven and structurally distinct from {@code java.lang.reflect}
   * (different bootstrap, different JIT shape), so verifying it independently catches any future
   * change that special-cases reflection but not method handles.
   *
   * <p>The WAL must contain exactly {@code n + 1} OPERATION entries for this method.
   *
   * @param n the recursion depth (non-negative)
   * @return the number of nested calls made (equal to {@code n})
   * @throws Throwable if the method-handle invocation throws (declared because {@link
   *     MethodHandle#invokeExact} is polymorphic and propagates the target's checked exceptions
   *     verbatim)
   */
  public int methodHandleRecursiveCount(int n) throws Throwable {
    if (n <= 0) {
      return 0;
    }
    return 1 + (int) MH_RECURSIVE_COUNT.invokeExact(this, n - 1);
  }

  /**
   * Recursive <em>static</em> method whose nested call goes through {@link Method#invoke(Object,
   * Object...)} with a {@code null} receiver, exercising {@code aroundVoid/NonVoidClassMethodsExec}
   * on the recursion path.
   *
   * <p>The instance variants exercise the instance-method advice; this variant verifies the
   * static-method advice clears the slot during proceed in the same way. Without that, the bug
   * would manifest identically on static recursion.
   *
   * <p>The WAL must contain exactly {@code n + 1} OPERATION entries for this method.
   *
   * @param n the recursion depth (non-negative)
   * @return the number of nested calls made (equal to {@code n})
   * @throws ReflectiveOperationException if the reflective lookup or invocation fails
   */
  public static int staticReflectiveRecursiveCount(int n) throws ReflectiveOperationException {
    if (n <= 0) {
      return 0;
    }
    Method m = ExecutionPointcutApp.class.getMethod("staticReflectiveRecursiveCount", int.class);
    return 1 + (int) m.invoke(null, n - 1);
  }

  /**
   * Half of the mutual-reflective-recursion pair: invokes {@link #mutualReflectiveCountB(int)}
   * reflectively. The chain alternates A → B → A → B → … until the depth reaches zero.
   *
   * <p>This case exercises a failure mode the single-method reflective recursion cannot: while
   * inside A's dispatch, A's key sits in the thread-local; A's body invokes B reflectively; B's
   * exec-site fires with TL = A's key (which does <em>not</em> match B's), so B dispatches; B's
   * body in turn invokes A reflectively, and the inner A's exec-site fires with TL still equal to
   * the outer A's key (in the buggy code path) — silently suppressing the inner A's dispatch. With
   * the slot cleared during the outer body's proceed, the inner A is captured.
   *
   * @param n the remaining recursion depth (non-negative)
   * @return the number of nested calls made (equal to {@code n})
   * @throws ReflectiveOperationException if the reflective lookup or invocation fails
   */
  public int mutualReflectiveCountA(int n) throws ReflectiveOperationException {
    if (n <= 0) {
      return 0;
    }
    Method b = ExecutionPointcutApp.class.getMethod("mutualReflectiveCountB", int.class);
    return 1 + (int) b.invoke(this, n - 1);
  }

  /**
   * Half of the mutual-reflective-recursion pair: invokes {@link #mutualReflectiveCountA(int)}
   * reflectively. See {@link #mutualReflectiveCountA(int)} for the failure mode being asserted.
   *
   * @param n the remaining recursion depth (non-negative)
   * @return the number of nested calls made (equal to {@code n})
   * @throws ReflectiveOperationException if the reflective lookup or invocation fails
   */
  public int mutualReflectiveCountB(int n) throws ReflectiveOperationException {
    if (n <= 0) {
      return 0;
    }
    Method a = ExecutionPointcutApp.class.getMethod("mutualReflectiveCountA", int.class);
    return 1 + (int) a.invoke(this, n - 1);
  }

  /**
   * Base class for the virtual-dispatch scenario. Its {@link #virtualMethod(String)} is overridden
   * by {@link VirtualSub}.
   */
  public static class VirtualBase {
    /**
     * Base implementation of the virtual method. Deliberately not invoked in the happy-path of
     * {@link ExecutionPointcutApp#main(String[])} — a {@link VirtualSub} overrides this.
     *
     * @param input the input string
     * @return {@code "base:" + input}
     */
    public String virtualMethod(String input) {
      return "base:" + input;
    }
  }

  /**
   * Subclass that overrides {@link VirtualBase#virtualMethod(String)}. Used to verify that a call
   * made through a {@link VirtualBase}-typed reference on a {@link VirtualSub} instance produces
   * exactly one WAL entry — the runtime-class-keyed guard must align call-site and execution-site
   * keys under virtual dispatch.
   */
  public static class VirtualSub extends VirtualBase {
    @Override
    public String virtualMethod(String input) {
      return "sub:" + input;
    }
  }

  /**
   * Interface used for the interface-dispatch scenario. Implemented by {@link VirtualIfaceImpl}.
   */
  public interface VirtualIface {
    /**
     * Interface method to be implemented. Call sites that reference {@code VirtualIface} resolve
     * their static type to the interface, while the execution happens on the concrete impl — the
     * guard key must pick the runtime class so both sides agree.
     *
     * @param input the input string
     * @return an implementation-specific string
     */
    String ifaceMethod(String input);
  }

  /**
   * Concrete implementation of {@link VirtualIface}. Its method body runs at the execution-site
   * when the call is made through a {@link VirtualIface}-typed reference.
   */
  public static class VirtualIfaceImpl implements VirtualIface {
    @Override
    public String ifaceMethod(String input) {
      return "iface:" + input;
    }
  }

  /**
   * Fixed recursion depth exercised by {@code main}; {@code RECURSION_DEPTH + 1} calls are made.
   */
  public static final int RECURSION_DEPTH = 3;

  /**
   * Exercises all invocation paths (direct, reflective, method-reference, static reflection,
   * lambda, reflective constructor, direct recursion, reflective recursion, lambda recursion,
   * method-handle recursion, static reflective recursion, mutual reflective recursion, virtual
   * dispatch, interface dispatch, framework-style callback via {@link Thread}) and prints a single
   * {@code results: ...} marker line.
   *
   * @param args command-line arguments (ignored)
   * @throws Throwable if any invocation path fails (declared because {@link
   *     MethodHandle#invokeExact} is polymorphic and propagates throwables verbatim)
   */
  public static void main(String[] args) throws Throwable {
    ExecutionPointcutApp app = new ExecutionPointcutApp();

    String r1 = app.normalMethod("hello");

    Method instanceMethod =
        ExecutionPointcutApp.class.getMethod("reflectedInstanceMethod", String.class);
    String r2 = (String) instanceMethod.invoke(app, "world");

    Function<String, String> ref = app::methodReferenceTarget;
    String r3 = ref.apply("ref");

    Method staticMethod =
        ExecutionPointcutApp.class.getMethod("reflectedStaticMethod", String.class);
    String r4 = (String) staticMethod.invoke(null, "static");

    Function<String, String> lam = x -> app.lambdaTarget(x);
    String r5 = lam.apply("lam");

    BiFunction<ExecutionPointcutApp, String, String> unboundRef =
        ExecutionPointcutApp::unboundRefTarget;
    String r5a = unboundRef.apply(app, "unb");

    Function<String, String> staticRef = ExecutionPointcutApp::staticRefTarget;
    String r5b = staticRef.apply("sref");

    Constructor<ExecutionPointcutApp> ctor =
        ExecutionPointcutApp.class.getConstructor(String.class);
    ExecutionPointcutApp reflectedApp = ctor.newInstance("ctor-marker");
    String r6 = reflectedApp.getMarker();

    int r7 = app.recursiveCount(RECURSION_DEPTH);

    int r7r = app.reflectiveRecursiveCount(RECURSION_DEPTH);

    int r7l = app.lambdaRecursiveCount(RECURSION_DEPTH);

    int r7m = app.methodHandleRecursiveCount(RECURSION_DEPTH);

    int r7s = staticReflectiveRecursiveCount(RECURSION_DEPTH);

    int r7mu = app.mutualReflectiveCountA(RECURSION_DEPTH);

    VirtualBase virtualRef = new VirtualSub();
    String r8 = virtualRef.virtualMethod("vd");

    VirtualIface ifaceRef = new VirtualIfaceImpl();
    String r9 = ifaceRef.ifaceMethod("id");

    Runnable worker = () -> app.frameworkCallbackResult = app.frameworkCallbackTarget("fw");
    Thread workerThread = new Thread(worker, "framework-callback");
    workerThread.start();
    workerThread.join();
    String r10 = app.frameworkCallbackResult;

    System.out.println(
        "results: "
            + r1
            + "|"
            + r2
            + "|"
            + r3
            + "|"
            + r4
            + "|"
            + r5
            + "|"
            + r5a
            + "|"
            + r5b
            + "|"
            + r6
            + "|"
            + r7
            + "|"
            + r7r
            + "|"
            + r7l
            + "|"
            + r7m
            + "|"
            + r7s
            + "|"
            + r7mu
            + "|"
            + r8
            + "|"
            + r9
            + "|"
            + r10);
  }
}
