###################################################################
# zk-kafka-peer-compose.yml
#
# CMD's (from `docker` dir):   docker-compose --project-directory .. -f zk-kafka-peer-compose.yml up/build/config
###################################################################

version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    network_mode: "host"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    network_mode: "host"
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      JMX_PORT: ${KAFKA_JMX_PORT}
      KAFKA_LISTENERS: INSIDE://:${KAFKA_INSIDE_PORT},OUTSIDE://:${KAFKA_OUTSIDE_PORT}
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:${KAFKA_INSIDE_PORT},OUTSIDE://_{HOSTNAME_COMMAND}:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: localhost:${ZOOKEEPER_LISTEN_PORT}
      KAFKA_LOG_DIRS: /data/kafka-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka-logs/docker:/data/kafka-logs

  peer:
    build:
      context: .
    image: peer
    network_mode: "host"
    env_file: peer.env
    depends_on:
      - zookeeper
      - kafka
    command: ["./wait-for", "localhost:${KAFKA_INSIDE_PORT}", "--", "./peer"]
