# ZMQ PROPERTIES
ZMQ_LINGER=1000
ZMQ_RCVHWM=10000
ZMQ_SNDHWM=10000


# KAFKA PROPERTIES
kafkaTopic=app.log
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=com.ittera.cometa.messages.protobuf.KafkaSerializer
pollTimeout=10
enable.auto.commit=true
auto.commit.interval.ms=500
auto.offset.reset=earliest
session.timeout.ms=30000
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=com.ittera.cometa.messages.protobuf.KafkaDeserializer


# PEER PROPERTIES
in.router=tcp://127.0.0.1:5671
in.log=inproc://inlog
in.dealer=inproc://deal
out.cell=inproc://cell
out.pub=inproc://pub
offset.pub=inproc://offsets

log.corePoolSize=10
log.maximumPoolSize=3000
log.keepAliveSeconds=60
peer.corePoolSize=5
peer.maximumPoolSize=3000
peer.keepAliveSeconds=60
