# ZMQ PROPERTIES
ZMQ_LINGER=1000
ZMQ_RCVHWM=10000
ZMQ_SNDHWM=10000

# KAFKA PROPERTIES
kafkaTopic=app.log
key.serializer=com.ittera.cometa.messages.protobuf.KafkaKeySerializer
value.serializer=com.ittera.cometa.messages.protobuf.KafkaSerializer
pollDuration=10
enable.auto.commit=true
auto.commit.interval.ms=500
auto.offset.reset=earliest
session.timeout.ms=30000
key.deserializer=com.ittera.cometa.messages.protobuf.KafkaKeyDeserializer
value.deserializer=com.ittera.cometa.messages.protobuf.KafkaDeserializer

# PEER PROPERTIES
in.req.tcp=tcp://localhost:5671
log.corePoolSize=3
log.maximumPoolSize=50
log.keepAliveSeconds=60
log.registerReplies=true
peer.corePoolSize=6
peer.maximumPoolSize=100
peer.keepAliveSeconds=60
