kafkaTopicPrefix=app.log
zookeeper.url=localhost:2181

## kafka 
# producer props
kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value.serializer=com.ittera.cometa.messages.protobuf.KafkaSerializer
# consumer props
kafka.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value.deserializer=com.ittera.cometa.messages.protobuf.KafkaDeserializer
kafka.consumer.auto.commit.interval.ms=1000
# own props
pollTimeout=10
