variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  KAFKA_LISTENERS: 'INSIDE://:9092,OUTSIDE://:9094'
  KAFKA_ADVERTISED_LISTENERS: 'INSIDE://:9092,OUTSIDE://kafka:9094'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'INSIDE'
  KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

image: maven:3.3.9-jdk-8

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

stages:
  - build
  - unit-tests
  - integration-tests
  - publish-artifacts

cache:
  paths:
    - .m2/repository

clean-install:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests

unit-tests:
  stage: unit-tests
  script:
    - mvn $MAVEN_CLI_OPTS test

integration-tests:
  stage: integration-tests
  variables:
    FF_NETWORK_PER_BUILD: 1
    PAL_DIRECTORY: 'zookeeper:2181'
    TCP_REQ: '5656'
    LOG: 'auto'
    JMX_HOST: 'localhost'
    JMX_PORT: 9012
  services:
    - name: wurstmeister/zookeeper:latest
      alias: zookeeper
    - name: wurstmeister/kafka:2.12-2.3.0
      alias: kafka
  script:
    - export PAL_VERSION=$(grep '<version>' pom.xml | head -1 | sed -E 's/.*<version>(.+)<\/version>.*/\1/')
    - export PAL_JAR=$CI_PROJECT_DIR/.m2/repository/net/ittera/pal/pal/$PAL_VERSION/pal-$PAL_VERSION.jar
    - export ITT_APPS_JAR=$CI_PROJECT_DIR/.m2/repository/net/ittera/pal/itt-apps/$PAL_VERSION/itt-apps-$PAL_VERSION.jar
    - cp $PAL_JAR . && bin/pal run --classpath $ITT_APPS_JAR &
    - mvn $MAVEN_CLI_OPTS verify -DskipUTs
  artifacts:
    when: on_failure
    paths:
      - itt/target/failsafe-reports
      - itt/logs
      - logs

publish-pal-image:
  stage: publish-artifacts
  image: docker:latest
  script:
    - export PAL_VERSION=$(grep '<version>' pom.xml | head -1 | sed -E 's/.*<version>(.+)<\/version>.*/\1/')
    - export PAL_JAR=$CI_PROJECT_DIR/.m2/repository/net/ittera/pal/pal/$PAL_VERSION/pal-$PAL_VERSION.jar
    - mkdir tools/target/ && cp -f $PAL_JAR tools/target/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f docker/Dockerfile --tag $CI_REGISTRY/cometera/pal/pal:latest .
    - docker push $CI_REGISTRY/cometera/pal/pal:latest
  only:
    - master

deploy-pal:
  stage: publish-artifacts
  script: 
    - mvn deploy -s ci_settings.xml -DskipTests
  only:
    - master
