enable.auto.commit=true
auto.commit.interval.ms=1000
session.timeout.ms=30000
key.deserializer=net.ittera.pal.serdes.kafka.typed.KafkaKeyDeserializer
value.deserializer=net.ittera.pal.serdes.kafka.typed.KafkaLogMessageDeserializer
