/*
   Copyright (c) 2020 Contributors listed in the AUTHORS file

   This file is part of PAL, the friendly java runtime.

   PAL is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   PAL is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

package net.ittera.pal.core.rpc;

import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import net.ittera.pal.core.ControlMessageDispatcher;
import net.ittera.pal.core.MetaMessageDispatcher;
import net.ittera.pal.core.rpc.exec.java.ClassMethodDispatcher;
import net.ittera.pal.core.rpc.exec.java.ConstructorDispatcher;
import net.ittera.pal.core.rpc.exec.java.GetClassVariableDispatcher;
import net.ittera.pal.core.rpc.exec.java.GetInstanceVariableDispatcher;
import net.ittera.pal.core.rpc.exec.java.InstanceMethodDispatcher;
import net.ittera.pal.core.rpc.exec.java.SetClassVariableDispatcher;
import net.ittera.pal.core.rpc.exec.java.SetInstanceVariableDispatcher;
import net.ittera.pal.messages.colfer.ControlMessage;
import net.ittera.pal.messages.colfer.ExecMessage;
import net.ittera.pal.messages.colfer.MetaMessage;
import net.ittera.pal.messages.types.MessageType;
import net.ittera.pal.serdes.colfer.ColferUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Routes incoming messages to their appropriate dispatcher components.
 *
 * <p>This class uses dependency injection to obtain various dispatchers responsible for handling
 * different types of messages, such as execution (exec), control, and meta messages. Depending on
 * the message type provided, the corresponding dispatcher is invoked to perform the necessary
 * operation, including method invocations, field access, or object construction.
 */
@Singleton
public class IncomingMessageDispatcher {

  /** Logger instance. */
  protected static final Logger logger = LoggerFactory.getLogger(IncomingMessageDispatcher.class);

  // constructor & method dispatchers

  /** Dispatcher that handles messages invoking constructor operations. */
  @SuppressWarnings("unused")
  @Inject
  private ConstructorDispatcher constructorDispatcher;

  /** Dispatcher that handles messages invoking static class methods. */
  @SuppressWarnings("unused")
  @Inject
  private ClassMethodDispatcher classMethodDispatcher;

  /** Dispatcher that handles messages invoking instance methods. */
  @SuppressWarnings("unused")
  @Inject
  private InstanceMethodDispatcher instanceMethodDispatcher;

  // field op dispatchers

  /** Dispatcher that handles retrieval of static field values. */
  @SuppressWarnings("unused")
  @Inject
  private GetClassVariableDispatcher getClassVariableDispatcher;

  /** Dispatcher that handles assignment to static fields. */
  @SuppressWarnings("unused")
  @Inject
  private SetClassVariableDispatcher setClassVariableDispatcher;

  /** Dispatcher that handles retrieval of instance field values. */
  @SuppressWarnings("unused")
  @Inject
  private GetInstanceVariableDispatcher getInstanceVariableDispatcher;

  /** Dispatcher that handles assignment to instance fields. */
  @SuppressWarnings("unused")
  @Inject
  private SetInstanceVariableDispatcher setInstanceVariableDispatcher;

  // control message dispatcher

  /** Dispatcher that processes control messages used for runtime management. */
  @SuppressWarnings("unused")
  @Inject
  private ControlMessageDispatcher controlMessageDispatcher;

  // meta message dispatcher

  /** Dispatcher that processes meta messages related to system metadata operations. */
  @SuppressWarnings("unused")
  @Inject
  private MetaMessageDispatcher metaMessageDispatcher;

  /**
   * Dispatches an execution message to its appropriate handler based on the specified message type.
   *
   * <p>This method examines the provided {@code messageType} and delegates the processing of the
   * associated {@code execMessage} to the corresponding dispatcher. The {@code isDirect} flag
   * indicates whether the message was received directly or retrieved from a log.
   *
   * @param execMessage the execution message containing invocation details
   * @param messageType the type of execution message that determines which dispatcher to invoke
   * @param isDirect {@code true} if the message is received directly; {@code false} if it
   *     originates from a log
   * @return the response execution message generated by the appropriate dispatcher
   * @throws UnsupportedMessageException if the provided message type does not map to any supported
   *     dispatcher
   */
  public ExecMessage incomingCall(
      ExecMessage execMessage, MessageType messageType, boolean isDirect) {

    return switch (messageType) {
      case EXEC_CONSTRUCTOR -> constructorDispatcher.dispatchIncoming(execMessage, isDirect);
      case EXEC_INSTANCE_METHOD -> instanceMethodDispatcher.dispatchIncoming(execMessage, isDirect);
      case EXEC_CLASS_METHOD -> classMethodDispatcher.dispatchIncoming(execMessage, isDirect);
      case EXEC_GET_STATIC -> getClassVariableDispatcher.dispatchIncoming(execMessage, isDirect);
      case EXEC_GET_FIELD -> getInstanceVariableDispatcher.dispatchIncoming(execMessage, isDirect);
      case EXEC_PUT_STATIC -> setClassVariableDispatcher.dispatchIncoming(execMessage, isDirect);
      case EXEC_PUT_FIELD -> setInstanceVariableDispatcher.dispatchIncoming(execMessage, isDirect);
      default ->
          throw new UnsupportedMessageException(
              String.format(
                  "Incoming exec message ignored - no handler:%n%s",
                  ColferUtils.format(execMessage)));
    };
  }

  /**
   * Delegates the provided control message to the control message dispatcher for processing.
   *
   * @param controlMessage the control message to be processed
   * @return the control message response after being handled by the dispatcher
   */
  public ControlMessage incomingControlMessage(ControlMessage controlMessage) {
    return controlMessageDispatcher.incomingControlMessage(controlMessage);
  }

  /**
   * Delegates the provided meta message to the meta message dispatcher for processing.
   *
   * @param metaMessage the meta message to be processed
   * @return the meta message response after being handled by the dispatcher
   */
  public MetaMessage incomingMetaMessage(MetaMessage metaMessage) {
    return metaMessageDispatcher.incomingMetaMessage(metaMessage);
  }
}
