#
# Copyright (C) 2026 Quasient Inc. <https://www.quasient.com>
#
# Use of this software is governed by the Business Source License 1.1
# included in the file LICENSE and at https://mariadb.com/bsl11
#
# Change Date: 2030-10-01
# Change License: Apache 2.0
#

enable.auto.commit=true
auto.commit.interval.ms=1000
session.timeout.ms=30000
key.deserializer=io.quasient.pal.serdes.kafka.typed.KafkaKeyDeserializer
value.deserializer=io.quasient.pal.serdes.kafka.typed.KafkaLogMessageDeserializer
