###################################################################
# etcd-peer-compose.yml
#
# CMD's (from `docker` dir):   docker-compose --project-directory .. -f etcd-peer-compose.yml up/config
###################################################################

networks:
  pal:
    driver: bridge

services:
  etcd:
    image: etcd:latest
    networks:
      - pal
    ports:
      - ${ETCD_CLIENT_PORT}:${ETCD_CLIENT_PORT}
      - ${ETCD_PEER_PORT}:${ETCD_PEER_PORT}
    command: ./etcd -name default
      -initial-advertise-peer-urls http://${HOST}:${ETCD_PEER_PORT}
      -listen-peer-urls http://0.0.0.0:${ETCD_PEER_PORT}
      -advertise-client-urls http://${HOST}:${ETCD_CLIENT_PORT}
      -listen-client-urls http://0.0.0.0:${ETCD_CLIENT_PORT}
      -initial-cluster default=http://${HOST}:${ETCD_PEER_PORT}

  peer:
    build:
      context: .
    image: pal
    networks:
      - pal
    env_file: peer.env
    depends_on:
      - etcd
