###################################################################
# etcd-kafka-peer-compose.yml
#
# CMD's (from `docker` dir):   docker-compose --project-directory $PAL_HOME -f etcd-kafka-peer-compose.yml up/build/config
###################################################################

networks:
  pal:
    driver: bridge

services:
  etcd:
    image: etcd:latest
    networks:
      - pal
    ports:
      - ${ETCD_CLIENT_PORT}:${ETCD_CLIENT_PORT}
      - ${ETCD_PEER_PORT}:${ETCD_PEER_PORT}
    command: ./etcd -name default
      -initial-advertise-peer-urls http://${HOST}:${ETCD_PEER_PORT}
      -listen-peer-urls http://0.0.0.0:${ETCD_PEER_PORT}
      -advertise-client-urls http://${HOST}:${ETCD_CLIENT_PORT}
      -listen-client-urls http://0.0.0.0:${ETCD_CLIENT_PORT}
      -initial-cluster default=http://${HOST}:${ETCD_PEER_PORT}

  kafka:
    image: apache/kafka:3.8.0
    networks:
      - pal
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
      - "${KAFKA_JMX_PORT}:${KAFKA_JMX_PORT}"
    environment:
      JMX_PORT: ${KAFKA_JMX_PORT}
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ulimits:
      nofile:
        soft: 1024
        hard: 1024

  peer:
    build:
      context: .
    image: pal
    network_mode: "bridge"
    env_file: peer.env
    depends_on:
      - etcd
      - kafka
    command: ["./wait-for", "kafka:${KAFKA_INTERNAL_PORT}", "--", "./pal"]
