kafkaTopicPrefix=app.log

## kafka 
# producer props
kafka.producer.key.serializer=com.ittera.cometa.messages.protobuf.KafkaKeySerializer
kafka.producer.value.serializer=com.ittera.cometa.messages.protobuf.KafkaSerializer
# consumer props
kafka.consumer.key.deserializer=com.ittera.cometa.messages.protobuf.KafkaKeyDeserializer
kafka.consumer.value.deserializer=com.ittera.cometa.messages.protobuf.KafkaDeserializer
kafka.consumer.auto.commit.interval.ms=1000
# own props
pollDuration=10
