/*
 * Copyright (C) 2026 Quasient Inc. <https://www.quasient.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quasient.pal.core.dispatcher.thread;

import io.quasient.pal.core.dispatcher.AbstractMessageInvokerThread;
import io.quasient.pal.core.dispatcher.IncomingMessageDispatcher;
import io.quasient.pal.core.transport.MessageChannelType;
import io.quasient.pal.core.transport.gateway.OutboundMessageGateway;
import io.quasient.pal.serdes.colfer.MessageBuilder;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.atomic.AtomicInteger;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.zeromq.ZContext;

/**
 * Abstract factory for creating and managing message invoker threads.
 *
 * <p>This class provides initialization of common resources for thread creation, such as thread
 * groups and configuration parameters, and tracks the threads generated by the factory for
 * subsequent management or cleanup.
 */
public abstract class InvokerThreadFactory implements ThreadFactory {

  /** List maintaining references to threads created by this factory. */
  private final List<Thread> createdThreads = new ArrayList<>();

  /** Thread group assigned to threads created by this factory. */
  protected ThreadGroup threadGroup;

  /** Counter for generating unique thread identifiers for new threads. */
  protected final AtomicInteger threadCounter = new AtomicInteger(0);

  /** Maximum priority to assign to threads in the thread group. */
  private static final int THREAD_GROUP_MAX_PRIORITY = Thread.NORM_PRIORITY;

  /** Indicates whether threads created by this factory should run as daemon threads. */
  private static final boolean THREAD_IS_DAEMON = false;

  /** Logger instance used for logging events and errors in the thread factory. */
  protected static final Logger logger = LoggerFactory.getLogger(InvokerThreadFactory.class);

  /** RPC channel type used to configure thread naming and logging. */
  private MessageChannelType messageChannelType;

  /** Builder used for constructing messages. */
  protected MessageBuilder messageBuilder;

  /** Connector responsible for dispatching messages to their intended destinations. */
  protected OutboundMessageGateway outboundMessageGateway;

  /** Dispatcher handling incoming messages. */
  protected IncomingMessageDispatcher incomingMessageDispatcher;

  // zmq stuff

  /** ZeroMQ context used for managing ZeroMQ sockets and communication. */
  protected ZContext zmqContext;

  /** Unique identifier for this peer. */
  protected UUID peerUuid;

  /** Class loader used to set the context for created threads. */
  private ClassLoader classLoader;

  /**
   * Initializes the thread factory with required communication contexts and parameters.
   *
   * <p>This method sets up the thread group, ZeroMQ context, message builder, dispatchers, class
   * loader, and peer identifier, and logs the initialization details.
   *
   * @param zmqContext the ZeroMQ context for socket management.
   * @param messageBuilder the builder used for creating messages.
   * @param incomingMessageDispatcher the dispatcher for handling incoming messages.
   * @param outboundMessageGateway the gateway for routing outgoing messages.
   * @param messageChannelType the type of RPC channel (e.g., SOCKET or LOG).
   * @param classLoader the class loader to assign to created threads.
   * @param peerUuid the unique identifier for the peer.
   */
  protected void init(
      ZContext zmqContext,
      MessageBuilder messageBuilder,
      IncomingMessageDispatcher incomingMessageDispatcher,
      OutboundMessageGateway outboundMessageGateway,
      MessageChannelType messageChannelType,
      ClassLoader classLoader,
      UUID peerUuid) {
    this.messageChannelType = messageChannelType;
    threadGroup = new ThreadGroup(getThreadGroupName());
    threadGroup.setMaxPriority(THREAD_GROUP_MAX_PRIORITY);
    this.zmqContext = zmqContext;
    this.messageBuilder = messageBuilder;
    this.outboundMessageGateway = outboundMessageGateway;
    this.incomingMessageDispatcher = incomingMessageDispatcher;
    this.classLoader = classLoader;
    this.peerUuid = peerUuid;
    logger.info(
        "Initialized exec thread factory with group name: {}, maxPriority: {}",
        getThreadGroupName(),
        THREAD_GROUP_MAX_PRIORITY);
  }

  /**
   * Creates an invoker thread with the specified name.
   *
   * <p>Subclasses must implement this method to instantiate an {@code AbstractMessageInvokerThread}
   * appropriate for the specific messaging channel/type.
   *
   * @param threadName the name to assign to the new invoker thread.
   * @return a new instance of {@code AbstractMessageInvokerThread}.
   */
  protected abstract AbstractMessageInvokerThread createInvokerThread(String threadName);

  /**
   * {@inheritDoc}
   *
   * <p>Creates a new invoker thread with a unique name, configures its class loader, daemon status,
   * and uncaught exception handler, and adds it to the list of created threads.
   *
   * @param r the runnable task to be executed by the new thread.
   * @return a newly created and configured thread.
   */
  @Override
  public Thread newThread(@SuppressWarnings("NullableProblems") Runnable r) {
    final String newThreadName = getThreadBaseName() + ' ' + threadCounter.getAndIncrement();
    final Thread thread = createInvokerThread(newThreadName);
    thread.setContextClassLoader(classLoader);
    thread.setDaemon(THREAD_IS_DAEMON);
    thread.setUncaughtExceptionHandler(
        (t, e) ->
            logger.error(
                "Uncaught exception in {} exec thread: {}",
                messageChannelType.getName(),
                newThreadName,
                e));
    addCreatedThread(thread);
    if (logger.isDebugEnabled()) {
      logger.debug(
          "Created new {} executor thread with name: '{}' and id: {}",
          messageChannelType.getName(),
          newThreadName,
          thread.getId());
    }
    return thread;
  }

  /**
   * Returns a shallow copy of the list of threads that have been created by this factory.
   *
   * <p>This list can be used for monitoring and managing the lifecycle of created threads.
   *
   * @return a shallow copy of the created threads list, suitable for iteration.
   */
  public List<Thread> getCreatedThreads() {
    return new ArrayList<>(createdThreads);
  }

  /**
   * Adds a thread to the internal list of created threads.
   *
   * @param t the thread to add.
   */
  private void addCreatedThread(Thread t) {
    createdThreads.add(t);
  }

  /**
   * Computes the base name used for naming newly created threads.
   *
   * <p>The base name incorporates the messaging channel type.
   *
   * @return a string representing the base name for threads.
   */
  protected String getThreadBaseName() {
    return String.format("%s Executor", messageChannelType.getName());
  }

  /**
   * Computes the name of the thread group for executor threads.
   *
   * <p>The thread group name is derived from the messaging channel type.
   *
   * @return a string representing the thread group name.
   */
  private String getThreadGroupName() {
    return String.format("%s Executor Group", messageChannelType.getName());
  }
}
