# ZMQ PROPERTIES
ZMQ_LINGER=1000
ZMQ_RCVHWM=10000
ZMQ_SNDHWM=10000

# KAFKA PROPERTIES
kafkaTopicPrefix=app
key.serializer=com.quasient.pal.serdes.kafka.KafkaKeySerializer
value.serializer=com.quasient.pal.serdes.kafka.KafkaMessageSerializer
pollDuration=10
enable.auto.commit=false
auto.commit.interval.ms=500
auto.offset.reset=earliest
session.timeout.ms=30000
key.deserializer=com.quasient.pal.serdes.kafka.KafkaKeyDeserializer
value.deserializer=com.quasient.pal.serdes.kafka.KafkaMessageDeserializer

# LOG PROPERTIES
log.threadPoolSize=1
