# ZMQ PROPERTIES
ZMQ_LINGER=1000
ZMQ_RCVHWM=10000
ZMQ_SNDHWM=10000

# KAFKA PROPERTIES
kafkaTopic=app
key.serializer=net.ittera.pal.messages.colfer.KafkaKeySerializer
value.serializer=net.ittera.pal.messages.colfer.KafkaSerializer
pollDuration=10
enable.auto.commit=true
auto.commit.interval.ms=500
auto.offset.reset=earliest
session.timeout.ms=30000
key.deserializer=net.ittera.pal.messages.colfer.KafkaKeyDeserializer
value.deserializer=net.ittera.pal.messages.colfer.KafkaDeserializer

# PEER PROPERTIES
log.corePoolSize=3
log.maximumPoolSize=50
log.keepAliveSeconds=60
log.registerReplies=false