id=1
kafkaTopic=test.data
### kafka properties
#common
kafka.bootstrap.servers=localhost:9092
#producer
kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value.serializer=com.ittera.cometa.concentrator.messages.protobuf.KafkaSerializer

