# zookeeper
zookeeper.url=localhost:2181

# zmq properties
in.router=tcp://127.0.0.1:5671
#in.router=ipc://router.ipc
in.log=tcp://*:9999
in.dealer=inproc://deal
out.cell=inproc://cell
out.pub=inproc://pub
offset.pub=inproc://offsets


# kafka properties
kafkaTopic=test.data
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=com.ittera.cometa.concentrator.messages.protobuf.KafkaSerializer
pollTimeout=10
enable.auto.commit=true
auto.commit.interval.ms=500
auto.offset.reset=earliest
session.timeout.ms=30000
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=com.ittera.cometa.concentrator.messages.protobuf.KafkaDeserializer

# log executor properties
log.corePoolSize=20
log.maximumPoolSize=3000
log.keepAliveSeconds=60

# peer executor properties
peer.corePoolSize=100
peer.maximumPoolSize=3000
peer.keepAliveSeconds=60
