id=10
kafkaTopic=test.data

### kafka properties
#common
kafka.bootstrap.servers=localhost:9092

#producer (used in Concentrator)
kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value.serializer=com.ittera.cometa.concentrator.messages.data.serde.ProtobufSerializer

#consumer (used in Dispatcher)
kafka.consumer.pollTimeout=10
kafka.consumer.enable.auto.commit=true
kafka.consumer.auto.commit.interval.ms=500
kafka.consumer.auto.offset.reset=earliest
kafka.consumer.session.timeout.ms=30000
kafka.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value.deserializer=com.ittera.cometa.concentrator.messages.data.serde.ProtobufDeserializer

### end kafka properties


exec.corePoolSize=0
#Integer.MAX_VALUE=2147483647
exec.maximumPoolSize=500
exec.keepAliveSeconds=60
