[distributor]
id=10
kafkaTopic=test.data
### kafka properties
#common
kafka.bootstrap.servers=localhost:9092
#producer (used in Distributor)
kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value.serializer=com.ittera.cometa.distributor.messages.ProtobufSerializer
#consumer (used in Dispatcher)
kafka.consumer.pollTimeout=10
kafka.consumer.enable.auto.commit=true
kafka.consumer.auto.commit.interval.ms=500
kafka.consumer.auto.offset.reset=latest
kafka.consumer.session.timeout.ms=30000
kafka.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value.deserializer=com.ittera.cometa.distributor.messages.ProtobufDeserializer
