###################################################################
# etcd-kafka-peer-compose.yml
#
# CMD's (from `docker` dir):   docker-compose --project-directory .. -f etcd-kafka-peer-compose.yml up/build/config
###################################################################

version: '3.7'

services:
  etcd:
    image: bitnami/etcd:3.5.0
    network_mode: "host"

  kafka:
    image: bitnami/kafka:3.3.2
    network_mode: "host"
    environment:
      HOSTNAME_COMMAND: "docker info | grep '^ *Name:' | tr -d ' ' | cut -d ':' -f 2"
      JMX_PORT: ${KAFKA_JMX_PORT}
      KAFKA_LISTENERS: INSIDE://:${KAFKA_INSIDE_PORT},OUTSIDE://:${KAFKA_OUTSIDE_PORT}
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:${KAFKA_INSIDE_PORT},OUTSIDE://_{HOSTNAME_COMMAND}:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  peer:
    build:
      context: .
    image: pal
    network_mode: "host"
    env_file: peer.env
    depends_on:
      - etcd
      - kafka
    command: ["./wait-for", "localhost:${KAFKA_INSIDE_PORT}", "--", "./pal"]
