###################################################################
# etcd-kafka-peer-compose.yml
#
# CMD's (from `docker` dir):   docker-compose --project-directory $PAL_HOME -f etcd-kafka-peer-compose.yml up/build/config
###################################################################

version: '3.7'

networks:
  pal:
    driver: bridge

services:
  etcd:
    image: etcd:latest
    networks:
      - pal
    ports:
      - '2379:2379'
      - '2380:2380'
    volumes:
      - type: bind
        source: $PAL_HOME/config/etcd
        target: /etc/etcd
    command: ./etcd --config-file /etc/etcd/etcd.conf.yml

  kafka:
    image: kafka:latest
    networks:
      - pal
    ports:
      - '9092:9092'
    volumes:
      - type: bind
        source: $PAL_HOME/config/kafka
        target: /etc/kafka
    command: format_start --config /etc/kafka/server.properties

  peer:
    build:
      context: .
    image: pal
    network_mode: "bridge"
    env_file: peer.env
    depends_on:
      - etcd
      - kafka
    command: ["./wait-for", "kafka:${KAFKA_INTERNAL_PORT}", "--", "./pal"]
