// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.ittera.cometa.messages.protobuf;

public final class Wrappers {
  private Wrappers() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface MessageOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:messages.protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
    boolean hasExecMessage();
    /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
    com.ittera.cometa.messages.protobuf.Exec.ExecMessage getExecMessage();
    /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
    com.ittera.cometa.messages.protobuf.Exec.ExecMessageOrBuilder getExecMessageOrBuilder();

    /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
    boolean hasInterceptMessage();
    /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
    com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage getInterceptMessage();
    /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
    com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessageOrBuilder
        getInterceptMessageOrBuilder();

    /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
    boolean hasInterceptReply();
    /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
    com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply getInterceptReply();
    /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
    com.ittera.cometa.messages.protobuf.Intercepts.InterceptReplyOrBuilder
        getInterceptReplyOrBuilder();

    public com.ittera.cometa.messages.protobuf.Wrappers.Message.ContentCase getContentCase();
  }
  /** Protobuf type {@code messages.protobuf.Message} */
  public static final class Message extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:messages.protobuf.Message)
      MessageOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Message() {}

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                com.ittera.cometa.messages.protobuf.Exec.ExecMessage.Builder subBuilder = null;
                if (contentCase_ == 1) {
                  subBuilder =
                      ((com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_).toBuilder();
                }
                content_ =
                    input.readMessage(
                        com.ittera.cometa.messages.protobuf.Exec.ExecMessage.PARSER,
                        extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(
                      (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_);
                  content_ = subBuilder.buildPartial();
                }
                contentCase_ = 1;
                break;
              }
            case 18:
              {
                com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.Builder subBuilder =
                    null;
                if (contentCase_ == 2) {
                  subBuilder =
                      ((com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_)
                          .toBuilder();
                }
                content_ =
                    input.readMessage(
                        com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.PARSER,
                        extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(
                      (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_);
                  content_ = subBuilder.buildPartial();
                }
                contentCase_ = 2;
                break;
              }
            case 26:
              {
                com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.Builder subBuilder =
                    null;
                if (contentCase_ == 3) {
                  subBuilder =
                      ((com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_)
                          .toBuilder();
                }
                content_ =
                    input.readMessage(
                        com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.PARSER,
                        extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(
                      (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_);
                  content_ = subBuilder.buildPartial();
                }
                contentCase_ = 3;
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.ittera.cometa.messages.protobuf.Wrappers
          .internal_static_messages_protobuf_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ittera.cometa.messages.protobuf.Wrappers
          .internal_static_messages_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ittera.cometa.messages.protobuf.Wrappers.Message.class,
              com.ittera.cometa.messages.protobuf.Wrappers.Message.Builder.class);
    }

    private int bitField0_;
    private int contentCase_ = 0;
    private java.lang.Object content_;

    public enum ContentCase implements com.google.protobuf.Internal.EnumLite {
      EXECMESSAGE(1),
      INTERCEPTMESSAGE(2),
      INTERCEPTREPLY(3),
      CONTENT_NOT_SET(0);
      private final int value;

      private ContentCase(int value) {
        this.value = value;
      }
      /** @deprecated Use {@link #forNumber(int)} instead. */
      @java.lang.Deprecated
      public static ContentCase valueOf(int value) {
        return forNumber(value);
      }

      public static ContentCase forNumber(int value) {
        switch (value) {
          case 1:
            return EXECMESSAGE;
          case 2:
            return INTERCEPTMESSAGE;
          case 3:
            return INTERCEPTREPLY;
          case 0:
            return CONTENT_NOT_SET;
          default:
            return null;
        }
      }

      public int getNumber() {
        return this.value;
      }
    };

    public ContentCase getContentCase() {
      return ContentCase.forNumber(contentCase_);
    }

    public static final int EXECMESSAGE_FIELD_NUMBER = 1;
    /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
    public boolean hasExecMessage() {
      return contentCase_ == 1;
    }
    /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
    public com.ittera.cometa.messages.protobuf.Exec.ExecMessage getExecMessage() {
      if (contentCase_ == 1) {
        return (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_;
      }
      return com.ittera.cometa.messages.protobuf.Exec.ExecMessage.getDefaultInstance();
    }
    /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
    public com.ittera.cometa.messages.protobuf.Exec.ExecMessageOrBuilder getExecMessageOrBuilder() {
      if (contentCase_ == 1) {
        return (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_;
      }
      return com.ittera.cometa.messages.protobuf.Exec.ExecMessage.getDefaultInstance();
    }

    public static final int INTERCEPTMESSAGE_FIELD_NUMBER = 2;
    /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
    public boolean hasInterceptMessage() {
      return contentCase_ == 2;
    }
    /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
    public com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage getInterceptMessage() {
      if (contentCase_ == 2) {
        return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_;
      }
      return com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.getDefaultInstance();
    }
    /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
    public com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessageOrBuilder
        getInterceptMessageOrBuilder() {
      if (contentCase_ == 2) {
        return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_;
      }
      return com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.getDefaultInstance();
    }

    public static final int INTERCEPTREPLY_FIELD_NUMBER = 3;
    /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
    public boolean hasInterceptReply() {
      return contentCase_ == 3;
    }
    /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
    public com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply getInterceptReply() {
      if (contentCase_ == 3) {
        return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_;
      }
      return com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.getDefaultInstance();
    }
    /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
    public com.ittera.cometa.messages.protobuf.Intercepts.InterceptReplyOrBuilder
        getInterceptReplyOrBuilder() {
      if (contentCase_ == 3) {
        return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_;
      }
      return com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasExecMessage()) {
        if (!getExecMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasInterceptMessage()) {
        if (!getInterceptMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasInterceptReply()) {
        if (!getInterceptReply().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (contentCase_ == 1) {
        output.writeMessage(1, (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_);
      }
      if (contentCase_ == 2) {
        output.writeMessage(
            2, (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_);
      }
      if (contentCase_ == 3) {
        output.writeMessage(
            3, (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (contentCase_ == 1) {
        size +=
            com.google.protobuf.CodedOutputStream.computeMessageSize(
                1, (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_);
      }
      if (contentCase_ == 2) {
        size +=
            com.google.protobuf.CodedOutputStream.computeMessageSize(
                2, (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_);
      }
      if (contentCase_ == 3) {
        size +=
            com.google.protobuf.CodedOutputStream.computeMessageSize(
                3, (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.ittera.cometa.messages.protobuf.Wrappers.Message)) {
        return super.equals(obj);
      }
      com.ittera.cometa.messages.protobuf.Wrappers.Message other =
          (com.ittera.cometa.messages.protobuf.Wrappers.Message) obj;

      if (!getContentCase().equals(other.getContentCase())) return false;
      switch (contentCase_) {
        case 1:
          if (!getExecMessage().equals(other.getExecMessage())) return false;
          break;
        case 2:
          if (!getInterceptMessage().equals(other.getInterceptMessage())) return false;
          break;
        case 3:
          if (!getInterceptReply().equals(other.getInterceptReply())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (contentCase_) {
        case 1:
          hash = (37 * hash) + EXECMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getExecMessage().hashCode();
          break;
        case 2:
          hash = (37 * hash) + INTERCEPTMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getInterceptMessage().hashCode();
          break;
        case 3:
          hash = (37 * hash) + INTERCEPTREPLY_FIELD_NUMBER;
          hash = (53 * hash) + getInterceptReply().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.ittera.cometa.messages.protobuf.Wrappers.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code messages.protobuf.Message} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:messages.protobuf.Message)
        com.ittera.cometa.messages.protobuf.Wrappers.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.ittera.cometa.messages.protobuf.Wrappers
            .internal_static_messages_protobuf_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ittera.cometa.messages.protobuf.Wrappers
            .internal_static_messages_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ittera.cometa.messages.protobuf.Wrappers.Message.class,
                com.ittera.cometa.messages.protobuf.Wrappers.Message.Builder.class);
      }

      // Construct using com.ittera.cometa.messages.protobuf.Wrappers.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        contentCase_ = 0;
        content_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.ittera.cometa.messages.protobuf.Wrappers
            .internal_static_messages_protobuf_Message_descriptor;
      }

      @java.lang.Override
      public com.ittera.cometa.messages.protobuf.Wrappers.Message getDefaultInstanceForType() {
        return com.ittera.cometa.messages.protobuf.Wrappers.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.ittera.cometa.messages.protobuf.Wrappers.Message build() {
        com.ittera.cometa.messages.protobuf.Wrappers.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ittera.cometa.messages.protobuf.Wrappers.Message buildPartial() {
        com.ittera.cometa.messages.protobuf.Wrappers.Message result =
            new com.ittera.cometa.messages.protobuf.Wrappers.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (contentCase_ == 1) {
          if (execMessageBuilder_ == null) {
            result.content_ = content_;
          } else {
            result.content_ = execMessageBuilder_.build();
          }
        }
        if (contentCase_ == 2) {
          if (interceptMessageBuilder_ == null) {
            result.content_ = content_;
          } else {
            result.content_ = interceptMessageBuilder_.build();
          }
        }
        if (contentCase_ == 3) {
          if (interceptReplyBuilder_ == null) {
            result.content_ = content_;
          } else {
            result.content_ = interceptReplyBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.contentCase_ = contentCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ittera.cometa.messages.protobuf.Wrappers.Message) {
          return mergeFrom((com.ittera.cometa.messages.protobuf.Wrappers.Message) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ittera.cometa.messages.protobuf.Wrappers.Message other) {
        if (other == com.ittera.cometa.messages.protobuf.Wrappers.Message.getDefaultInstance())
          return this;
        switch (other.getContentCase()) {
          case EXECMESSAGE:
            {
              mergeExecMessage(other.getExecMessage());
              break;
            }
          case INTERCEPTMESSAGE:
            {
              mergeInterceptMessage(other.getInterceptMessage());
              break;
            }
          case INTERCEPTREPLY:
            {
              mergeInterceptReply(other.getInterceptReply());
              break;
            }
          case CONTENT_NOT_SET:
            {
              break;
            }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasExecMessage()) {
          if (!getExecMessage().isInitialized()) {
            return false;
          }
        }
        if (hasInterceptMessage()) {
          if (!getInterceptMessage().isInitialized()) {
            return false;
          }
        }
        if (hasInterceptReply()) {
          if (!getInterceptReply().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ittera.cometa.messages.protobuf.Wrappers.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.ittera.cometa.messages.protobuf.Wrappers.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int contentCase_ = 0;
      private java.lang.Object content_;

      public ContentCase getContentCase() {
        return ContentCase.forNumber(contentCase_);
      }

      public Builder clearContent() {
        contentCase_ = 0;
        content_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.messages.protobuf.Exec.ExecMessage,
              com.ittera.cometa.messages.protobuf.Exec.ExecMessage.Builder,
              com.ittera.cometa.messages.protobuf.Exec.ExecMessageOrBuilder>
          execMessageBuilder_;
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public boolean hasExecMessage() {
        return contentCase_ == 1;
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public com.ittera.cometa.messages.protobuf.Exec.ExecMessage getExecMessage() {
        if (execMessageBuilder_ == null) {
          if (contentCase_ == 1) {
            return (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_;
          }
          return com.ittera.cometa.messages.protobuf.Exec.ExecMessage.getDefaultInstance();
        } else {
          if (contentCase_ == 1) {
            return execMessageBuilder_.getMessage();
          }
          return com.ittera.cometa.messages.protobuf.Exec.ExecMessage.getDefaultInstance();
        }
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public Builder setExecMessage(com.ittera.cometa.messages.protobuf.Exec.ExecMessage value) {
        if (execMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          execMessageBuilder_.setMessage(value);
        }
        contentCase_ = 1;
        return this;
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public Builder setExecMessage(
          com.ittera.cometa.messages.protobuf.Exec.ExecMessage.Builder builderForValue) {
        if (execMessageBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          execMessageBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 1;
        return this;
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public Builder mergeExecMessage(com.ittera.cometa.messages.protobuf.Exec.ExecMessage value) {
        if (execMessageBuilder_ == null) {
          if (contentCase_ == 1
              && content_
                  != com.ittera.cometa.messages.protobuf.Exec.ExecMessage.getDefaultInstance()) {
            content_ =
                com.ittera.cometa.messages.protobuf.Exec.ExecMessage.newBuilder(
                        (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_)
                    .mergeFrom(value)
                    .buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 1) {
            execMessageBuilder_.mergeFrom(value);
          }
          execMessageBuilder_.setMessage(value);
        }
        contentCase_ = 1;
        return this;
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public Builder clearExecMessage() {
        if (execMessageBuilder_ == null) {
          if (contentCase_ == 1) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 1) {
            contentCase_ = 0;
            content_ = null;
          }
          execMessageBuilder_.clear();
        }
        return this;
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public com.ittera.cometa.messages.protobuf.Exec.ExecMessage.Builder getExecMessageBuilder() {
        return getExecMessageFieldBuilder().getBuilder();
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      public com.ittera.cometa.messages.protobuf.Exec.ExecMessageOrBuilder
          getExecMessageOrBuilder() {
        if ((contentCase_ == 1) && (execMessageBuilder_ != null)) {
          return execMessageBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 1) {
            return (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_;
          }
          return com.ittera.cometa.messages.protobuf.Exec.ExecMessage.getDefaultInstance();
        }
      }
      /** <code>optional .messages.protobuf.ExecMessage execMessage = 1;</code> */
      private com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.messages.protobuf.Exec.ExecMessage,
              com.ittera.cometa.messages.protobuf.Exec.ExecMessage.Builder,
              com.ittera.cometa.messages.protobuf.Exec.ExecMessageOrBuilder>
          getExecMessageFieldBuilder() {
        if (execMessageBuilder_ == null) {
          if (!(contentCase_ == 1)) {
            content_ = com.ittera.cometa.messages.protobuf.Exec.ExecMessage.getDefaultInstance();
          }
          execMessageBuilder_ =
              new com.google.protobuf.SingleFieldBuilderV3<
                  com.ittera.cometa.messages.protobuf.Exec.ExecMessage,
                  com.ittera.cometa.messages.protobuf.Exec.ExecMessage.Builder,
                  com.ittera.cometa.messages.protobuf.Exec.ExecMessageOrBuilder>(
                  (com.ittera.cometa.messages.protobuf.Exec.ExecMessage) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 1;
        onChanged();
        ;
        return execMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.Builder,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessageOrBuilder>
          interceptMessageBuilder_;
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public boolean hasInterceptMessage() {
        return contentCase_ == 2;
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage getInterceptMessage() {
        if (interceptMessageBuilder_ == null) {
          if (contentCase_ == 2) {
            return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_;
          }
          return com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage
              .getDefaultInstance();
        } else {
          if (contentCase_ == 2) {
            return interceptMessageBuilder_.getMessage();
          }
          return com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage
              .getDefaultInstance();
        }
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public Builder setInterceptMessage(
          com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage value) {
        if (interceptMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          interceptMessageBuilder_.setMessage(value);
        }
        contentCase_ = 2;
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public Builder setInterceptMessage(
          com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.Builder builderForValue) {
        if (interceptMessageBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          interceptMessageBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 2;
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public Builder mergeInterceptMessage(
          com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage value) {
        if (interceptMessageBuilder_ == null) {
          if (contentCase_ == 2
              && content_
                  != com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage
                      .getDefaultInstance()) {
            content_ =
                com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.newBuilder(
                        (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_)
                    .mergeFrom(value)
                    .buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 2) {
            interceptMessageBuilder_.mergeFrom(value);
          }
          interceptMessageBuilder_.setMessage(value);
        }
        contentCase_ = 2;
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public Builder clearInterceptMessage() {
        if (interceptMessageBuilder_ == null) {
          if (contentCase_ == 2) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 2) {
            contentCase_ = 0;
            content_ = null;
          }
          interceptMessageBuilder_.clear();
        }
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.Builder
          getInterceptMessageBuilder() {
        return getInterceptMessageFieldBuilder().getBuilder();
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      public com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessageOrBuilder
          getInterceptMessageOrBuilder() {
        if ((contentCase_ == 2) && (interceptMessageBuilder_ != null)) {
          return interceptMessageBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 2) {
            return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_;
          }
          return com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage
              .getDefaultInstance();
        }
      }
      /** <code>optional .messages.protobuf.InterceptMessage interceptMessage = 2;</code> */
      private com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.Builder,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessageOrBuilder>
          getInterceptMessageFieldBuilder() {
        if (interceptMessageBuilder_ == null) {
          if (!(contentCase_ == 2)) {
            content_ =
                com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage
                    .getDefaultInstance();
          }
          interceptMessageBuilder_ =
              new com.google.protobuf.SingleFieldBuilderV3<
                  com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage,
                  com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage.Builder,
                  com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessageOrBuilder>(
                  (com.ittera.cometa.messages.protobuf.Intercepts.InterceptMessage) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 2;
        onChanged();
        ;
        return interceptMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.Builder,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptReplyOrBuilder>
          interceptReplyBuilder_;
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public boolean hasInterceptReply() {
        return contentCase_ == 3;
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply getInterceptReply() {
        if (interceptReplyBuilder_ == null) {
          if (contentCase_ == 3) {
            return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_;
          }
          return com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.getDefaultInstance();
        } else {
          if (contentCase_ == 3) {
            return interceptReplyBuilder_.getMessage();
          }
          return com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.getDefaultInstance();
        }
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public Builder setInterceptReply(
          com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply value) {
        if (interceptReplyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          interceptReplyBuilder_.setMessage(value);
        }
        contentCase_ = 3;
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public Builder setInterceptReply(
          com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.Builder builderForValue) {
        if (interceptReplyBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          interceptReplyBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 3;
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public Builder mergeInterceptReply(
          com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply value) {
        if (interceptReplyBuilder_ == null) {
          if (contentCase_ == 3
              && content_
                  != com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply
                      .getDefaultInstance()) {
            content_ =
                com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.newBuilder(
                        (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_)
                    .mergeFrom(value)
                    .buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 3) {
            interceptReplyBuilder_.mergeFrom(value);
          }
          interceptReplyBuilder_.setMessage(value);
        }
        contentCase_ = 3;
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public Builder clearInterceptReply() {
        if (interceptReplyBuilder_ == null) {
          if (contentCase_ == 3) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 3) {
            contentCase_ = 0;
            content_ = null;
          }
          interceptReplyBuilder_.clear();
        }
        return this;
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.Builder
          getInterceptReplyBuilder() {
        return getInterceptReplyFieldBuilder().getBuilder();
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      public com.ittera.cometa.messages.protobuf.Intercepts.InterceptReplyOrBuilder
          getInterceptReplyOrBuilder() {
        if ((contentCase_ == 3) && (interceptReplyBuilder_ != null)) {
          return interceptReplyBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 3) {
            return (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_;
          }
          return com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.getDefaultInstance();
        }
      }
      /** <code>optional .messages.protobuf.InterceptReply interceptReply = 3;</code> */
      private com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.Builder,
              com.ittera.cometa.messages.protobuf.Intercepts.InterceptReplyOrBuilder>
          getInterceptReplyFieldBuilder() {
        if (interceptReplyBuilder_ == null) {
          if (!(contentCase_ == 3)) {
            content_ =
                com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.getDefaultInstance();
          }
          interceptReplyBuilder_ =
              new com.google.protobuf.SingleFieldBuilderV3<
                  com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply,
                  com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply.Builder,
                  com.ittera.cometa.messages.protobuf.Intercepts.InterceptReplyOrBuilder>(
                  (com.ittera.cometa.messages.protobuf.Intercepts.InterceptReply) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 3;
        onChanged();
        ;
        return interceptReplyBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:messages.protobuf.Message)
    }

    // @@protoc_insertion_point(class_scope:messages.protobuf.Message)
    private static final com.ittera.cometa.messages.protobuf.Wrappers.Message DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.ittera.cometa.messages.protobuf.Wrappers.Message();
    }

    public static com.ittera.cometa.messages.protobuf.Wrappers.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
          @java.lang.Override
          public Message parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Message(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ittera.cometa.messages.protobuf.Wrappers.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_messages_protobuf_Message_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_protobuf_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\016wrappers.proto\022\021messages.protobuf\032\nexe"
          + "c.proto\032\020intercepts.proto\"\311\001\n\007Message\0225\n"
          + "\013execMessage\030\001 \001(\0132\036.messages.protobuf.E"
          + "xecMessageH\000\022?\n\020interceptMessage\030\002 \001(\0132#"
          + ".messages.protobuf.InterceptMessageH\000\022;\n"
          + "\016interceptReply\030\003 \001(\0132!.messages.protobu"
          + "f.InterceptReplyH\000B\t\n\007contentB\'\n#com.itt"
          + "era.cometa.messages.protobufH\001"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.ittera.cometa.messages.protobuf.Exec.getDescriptor(),
              com.ittera.cometa.messages.protobuf.Intercepts.getDescriptor(),
            });
    internal_static_messages_protobuf_Message_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_messages_protobuf_Message_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_messages_protobuf_Message_descriptor,
            new java.lang.String[] {
              "ExecMessage", "InterceptMessage", "InterceptReply", "Content",
            });
    com.ittera.cometa.messages.protobuf.Exec.getDescriptor();
    com.ittera.cometa.messages.protobuf.Intercepts.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
