/*
 * Copyright (C) 2026 Quasient Inc. <https://www.quasient.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quasient.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, meta.colf, primitives.colf, values.colf,
// wrappers.colf and calls.colf.

import static java.lang.String.format;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class ConstructorCall implements Serializable, io.quasient.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  /** The upper limit for the number of elements in a list. */
  public static int colferListMax = 64 * 1024;

  public Class clazz;

  public int modifiers;

  public Parameter[] parameters;

  public Context context;

  /** Default constructor */
  public ConstructorCall() {
    init();
  }

  private static final Parameter[] _zeroParameters = new Parameter[0];

  /** Colfer zero values. */
  private void init() {
    parameters = _zeroParameters;
  }

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(ConstructorCall.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax}
     *     or {@link #colferListMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public ConstructorCall next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            ConstructorCall o = new ConstructorCall();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(ConstructorCall.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n = 1L + 5 + 6;
    if (this.clazz != null) n += 1 + (long) this.clazz.marshalFit();
    for (Parameter o : this.parameters) {
      if (o == null) n++;
      else n += o.marshalFit();
    }
    if (this.context != null) n += 1 + (long) this.context.marshalFit();
    if (n < 0 || n > (long) ConstructorCall.colferSizeMax) return ConstructorCall.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object. All {@code null} elements in {@link #parameters} will be replaced with a
   * {@code new} value.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax}
   *     or {@link #colferListMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object. All {@code null} elements in {@link #parameters} will be replaced with a
   * {@code new} value.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax}
   *     or {@link #colferListMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (this.clazz != null) {
        buf[i++] = (byte) 0;
        i = this.clazz.marshal(buf, i);
      }

      if (this.modifiers != 0) {
        int x = this.modifiers;
        if ((x & ~((1 << 21) - 1)) != 0) {
          buf[i++] = (byte) (1 | 0x80);
          buf[i++] = (byte) (x >>> 24);
          buf[i++] = (byte) (x >>> 16);
          buf[i++] = (byte) (x >>> 8);
        } else {
          buf[i++] = (byte) 1;
          while (x > 0x7f) {
            buf[i++] = (byte) (x | 0x80);
            x >>>= 7;
          }
        }
        buf[i++] = (byte) x;
      }

      if (this.parameters.length != 0) {
        buf[i++] = (byte) 2;
        Parameter[] a = this.parameters;

        int x = a.length;
        if (x > ConstructorCall.colferListMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.ConstructorCall.parameters length %d exceeds %d elements",
                  x, ConstructorCall.colferListMax));
        while (x > 0x7f) {
          buf[i++] = (byte) (x | 0x80);
          x >>>= 7;
        }
        buf[i++] = (byte) x;

        for (int ai = 0; ai < a.length; ai++) {
          Parameter o = a[ai];
          if (o == null) {
            o = new Parameter();
            a[ai] = o;
          }
          i = o.marshal(buf, i);
        }
      }

      if (this.context != null) {
        buf[i++] = (byte) 3;
        i = this.context.marshal(buf, i);
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > ConstructorCall.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: io.quasient.pal.messages/colfer.ConstructorCall exceeds %d bytes",
                ConstructorCall.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or
   *     {@link #colferListMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or
   *     {@link #colferListMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        this.clazz = new Class();
        i = this.clazz.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        int x = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          x |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        this.modifiers = x;
        header = buf[i++];
      } else if (header == (byte) (1 | 0x80)) {
        this.modifiers =
            (buf[i++] & 0xff) << 24
                | (buf[i++] & 0xff) << 16
                | (buf[i++] & 0xff) << 8
                | (buf[i++] & 0xff);
        header = buf[i++];
      }

      if (header == (byte) 2) {
        int length = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          length |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (length < 0 || length > ConstructorCall.colferListMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.ConstructorCall.parameters length %d exceeds %d elements",
                  length, ConstructorCall.colferListMax));

        Parameter[] a = new Parameter[length];
        for (int ai = 0; ai < length; ai++) {
          Parameter o = new Parameter();
          i = o.unmarshal(buf, i, end);
          a[ai] = o;
        }
        this.parameters = a;
        header = buf[i++];
      }

      if (header == (byte) 3) {
        this.context = new Context();
        i = this.context.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < ConstructorCall.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > ConstructorCall.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: io.quasient.pal.messages/colfer.ConstructorCall exceeds %d bytes",
                ConstructorCall.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 4L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets io.quasient.pal.messages/colfer.ConstructorCall.clazz.
   *
   * @return the value.
   */
  public Class getClazz() {
    return this.clazz;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.clazz.
   *
   * @param value the replacement.
   */
  public void setClazz(Class value) {
    this.clazz = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.clazz.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ConstructorCall withClazz(Class value) {
    this.clazz = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.ConstructorCall.modifiers.
   *
   * @return the value.
   */
  public int getModifiers() {
    return this.modifiers;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.modifiers.
   *
   * @param value the replacement.
   */
  public void setModifiers(int value) {
    this.modifiers = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.modifiers.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ConstructorCall withModifiers(int value) {
    this.modifiers = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.ConstructorCall.parameters.
   *
   * @return the value.
   */
  public Parameter[] getParameters() {
    return this.parameters;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.parameters.
   *
   * @param value the replacement.
   */
  public void setParameters(Parameter[] value) {
    this.parameters = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.parameters.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ConstructorCall withParameters(Parameter[] value) {
    this.parameters = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.ConstructorCall.context.
   *
   * @return the value.
   */
  public Context getContext() {
    return this.context;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.context.
   *
   * @param value the replacement.
   */
  public void setContext(Context value) {
    this.context = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.ConstructorCall.context.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ConstructorCall withContext(Context value) {
    this.context = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.clazz != null) h = 31 * h + this.clazz.hashCode();
    h = 31 * h + this.modifiers;
    for (Parameter o : this.parameters) h = 31 * h + (o == null ? 0 : o.hashCode());
    if (this.context != null) h = 31 * h + this.context.hashCode();
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof ConstructorCall && equals((ConstructorCall) o);
  }

  public final boolean equals(ConstructorCall o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.clazz == null ? o.clazz == null : this.clazz.equals(o.clazz))
        && this.modifiers == o.modifiers
        && java.util.Arrays.equals(this.parameters, o.parameters)
        && (this.context == null ? o.context == null : this.context.equals(o.context));
  }

  @Override
  public ConstructorCall fromJson(JsonObject json) throws JsonParseException {
    try {
      if (json.has("clazz")) {
        JsonObject jsonObj = json.getAsJsonObject("clazz");
        this.clazz = new Class().fromJson(jsonObj);
      }

      if (json.has("modifiers")) {
        this.modifiers = json.get("modifiers").getAsInt();
      }

      if (json.has("parameters")) {
        JsonArray jsonArray = json.getAsJsonArray("parameters");
        this.parameters = new Parameter[jsonArray.size()];
        for (int i = 0; i < jsonArray.size(); i++) {
          JsonObject jsonObj = jsonArray.get(i).getAsJsonObject();
          this.parameters[i] = new Parameter().fromJson(jsonObj);
        }
      }
      if (json.has("context")) {
        JsonObject jsonObj = json.getAsJsonObject("context");
        this.context = new Context().fromJson(jsonObj);
      }

    } catch (Exception e) {
      throw new JsonParseException("Error deserializing json object: " + e.getMessage(), e);
    }
    return this;
  }

  /**
   * Resets this Colfer message to its zero state for reuse on the hot path. Calls init(), then
   * zeros primitives and nulls nested messages.
   */
  public void reset() {
    init();
    this.clazz = null;
    this.modifiers = 0;
    this.context = null;
  }
}
