/*
 * Copyright (C) 2025 Quasient Inc. <https://www.quasient.com>
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in the file LICENSE and at https://mariadb.com/bsl11
 *
 * Change Date: 2029-10-01
 * Change License: Apache 2.0
 */
package io.quasient.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, meta.colf, primitives.colf, values.colf,
// wrappers.colf and calls.colf.

import static java.lang.String.format;

import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class InstanceFieldPut implements Serializable, io.quasient.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  public Class clazz;

  public int objectRef;

  public Field field;

  public Obj valueObject;

  public int valueObjectRef;

  public Context context;

  /** Default constructor */
  public InstanceFieldPut() {
    init();
  }

  /** Colfer zero values. */
  private void init() {}

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(InstanceFieldPut.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public InstanceFieldPut next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            InstanceFieldPut o = new InstanceFieldPut();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(InstanceFieldPut.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n = 1L + 5 + 5;
    if (this.clazz != null) n += 1 + (long) this.clazz.marshalFit();
    if (this.field != null) n += 1 + (long) this.field.marshalFit();
    if (this.valueObject != null) n += 1 + (long) this.valueObject.marshalFit();
    if (this.context != null) n += 1 + (long) this.context.marshalFit();
    if (n < 0 || n > (long) InstanceFieldPut.colferSizeMax) return InstanceFieldPut.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (this.clazz != null) {
        buf[i++] = (byte) 0;
        i = this.clazz.marshal(buf, i);
      }

      if (this.objectRef != 0) {
        int x = this.objectRef;
        if ((x & ~((1 << 21) - 1)) != 0) {
          buf[i++] = (byte) (1 | 0x80);
          buf[i++] = (byte) (x >>> 24);
          buf[i++] = (byte) (x >>> 16);
          buf[i++] = (byte) (x >>> 8);
        } else {
          buf[i++] = (byte) 1;
          while (x > 0x7f) {
            buf[i++] = (byte) (x | 0x80);
            x >>>= 7;
          }
        }
        buf[i++] = (byte) x;
      }

      if (this.field != null) {
        buf[i++] = (byte) 2;
        i = this.field.marshal(buf, i);
      }

      if (this.valueObject != null) {
        buf[i++] = (byte) 3;
        i = this.valueObject.marshal(buf, i);
      }

      if (this.valueObjectRef != 0) {
        int x = this.valueObjectRef;
        if ((x & ~((1 << 21) - 1)) != 0) {
          buf[i++] = (byte) (4 | 0x80);
          buf[i++] = (byte) (x >>> 24);
          buf[i++] = (byte) (x >>> 16);
          buf[i++] = (byte) (x >>> 8);
        } else {
          buf[i++] = (byte) 4;
          while (x > 0x7f) {
            buf[i++] = (byte) (x | 0x80);
            x >>>= 7;
          }
        }
        buf[i++] = (byte) x;
      }

      if (this.context != null) {
        buf[i++] = (byte) 5;
        i = this.context.marshal(buf, i);
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > InstanceFieldPut.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InstanceFieldPut exceeds %d bytes",
                InstanceFieldPut.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        this.clazz = new Class();
        i = this.clazz.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        int x = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          x |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        this.objectRef = x;
        header = buf[i++];
      } else if (header == (byte) (1 | 0x80)) {
        this.objectRef =
            (buf[i++] & 0xff) << 24
                | (buf[i++] & 0xff) << 16
                | (buf[i++] & 0xff) << 8
                | (buf[i++] & 0xff);
        header = buf[i++];
      }

      if (header == (byte) 2) {
        this.field = new Field();
        i = this.field.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 3) {
        this.valueObject = new Obj();
        i = this.valueObject.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 4) {
        int x = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          x |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        this.valueObjectRef = x;
        header = buf[i++];
      } else if (header == (byte) (4 | 0x80)) {
        this.valueObjectRef =
            (buf[i++] & 0xff) << 24
                | (buf[i++] & 0xff) << 16
                | (buf[i++] & 0xff) << 8
                | (buf[i++] & 0xff);
        header = buf[i++];
      }

      if (header == (byte) 5) {
        this.context = new Context();
        i = this.context.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < InstanceFieldPut.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > InstanceFieldPut.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InstanceFieldPut exceeds %d bytes",
                InstanceFieldPut.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 6L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InstanceFieldPut.clazz.
   *
   * @return the value.
   */
  public Class getClazz() {
    return this.clazz;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.clazz.
   *
   * @param value the replacement.
   */
  public void setClazz(Class value) {
    this.clazz = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.clazz.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldPut withClazz(Class value) {
    this.clazz = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InstanceFieldPut.objectRef.
   *
   * @return the value.
   */
  public int getObjectRef() {
    return this.objectRef;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.objectRef.
   *
   * @param value the replacement.
   */
  public void setObjectRef(int value) {
    this.objectRef = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.objectRef.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldPut withObjectRef(int value) {
    this.objectRef = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InstanceFieldPut.field.
   *
   * @return the value.
   */
  public Field getField() {
    return this.field;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.field.
   *
   * @param value the replacement.
   */
  public void setField(Field value) {
    this.field = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.field.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldPut withField(Field value) {
    this.field = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InstanceFieldPut.valueObject.
   *
   * @return the value.
   */
  public Obj getValueObject() {
    return this.valueObject;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.valueObject.
   *
   * @param value the replacement.
   */
  public void setValueObject(Obj value) {
    this.valueObject = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.valueObject.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldPut withValueObject(Obj value) {
    this.valueObject = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InstanceFieldPut.valueObjectRef.
   *
   * @return the value.
   */
  public int getValueObjectRef() {
    return this.valueObjectRef;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.valueObjectRef.
   *
   * @param value the replacement.
   */
  public void setValueObjectRef(int value) {
    this.valueObjectRef = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.valueObjectRef.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldPut withValueObjectRef(int value) {
    this.valueObjectRef = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InstanceFieldPut.context.
   *
   * @return the value.
   */
  public Context getContext() {
    return this.context;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.context.
   *
   * @param value the replacement.
   */
  public void setContext(Context value) {
    this.context = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InstanceFieldPut.context.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldPut withContext(Context value) {
    this.context = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.clazz != null) h = 31 * h + this.clazz.hashCode();
    h = 31 * h + this.objectRef;
    if (this.field != null) h = 31 * h + this.field.hashCode();
    if (this.valueObject != null) h = 31 * h + this.valueObject.hashCode();
    h = 31 * h + this.valueObjectRef;
    if (this.context != null) h = 31 * h + this.context.hashCode();
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof InstanceFieldPut && equals((InstanceFieldPut) o);
  }

  public final boolean equals(InstanceFieldPut o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.clazz == null ? o.clazz == null : this.clazz.equals(o.clazz))
        && this.objectRef == o.objectRef
        && (this.field == null ? o.field == null : this.field.equals(o.field))
        && (this.valueObject == null
            ? o.valueObject == null
            : this.valueObject.equals(o.valueObject))
        && this.valueObjectRef == o.valueObjectRef
        && (this.context == null ? o.context == null : this.context.equals(o.context));
  }

  @Override
  public InstanceFieldPut fromJson(JsonObject json) throws JsonParseException {
    try {
      if (json.has("clazz")) {
        JsonObject jsonObj = json.getAsJsonObject("clazz");
        this.clazz = new Class().fromJson(jsonObj);
      }

      if (json.has("objectRef")) {
        this.objectRef = json.get("objectRef").getAsInt();
      }

      if (json.has("field")) {
        JsonObject jsonObj = json.getAsJsonObject("field");
        this.field = new Field().fromJson(jsonObj);
      }

      if (json.has("valueObject")) {
        JsonObject jsonObj = json.getAsJsonObject("valueObject");
        this.valueObject = new Obj().fromJson(jsonObj);
      }

      if (json.has("valueObjectRef")) {
        this.valueObjectRef = json.get("valueObjectRef").getAsInt();
      }

      if (json.has("context")) {
        JsonObject jsonObj = json.getAsJsonObject("context");
        this.context = new Context().fromJson(jsonObj);
      }

    } catch (Exception e) {
      throw new JsonParseException("Error deserializing json object: " + e.getMessage(), e);
    }
    return this;
  }

  /**
   * Resets this Colfer message to its zero state for reuse on the hot path. Calls init(), then
   * zeros primitives and nulls nested messages.
   */
  public void reset() {
    init();
    this.clazz = null;
    this.objectRef = 0;
    this.field = null;
    this.valueObject = null;
    this.valueObjectRef = 0;
    this.context = null;
  }
}
