/*
 * Copyright (C) 2026 Quasient Inc. <https://www.quasient.com>
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in the file LICENSE and at https://mariadb.com/bsl11
 *
 * Change Date: 2030-10-01
 * Change License: Apache 2.0
 */
package io.quasient.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, meta.colf, primitives.colf, values.colf,
// wrappers.colf and calls.colf.

import static java.lang.String.format;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class InterceptCallbackResponseMessage
    implements Serializable, io.quasient.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  /** The upper limit for the number of elements in a list. */
  public static int colferListMax = 64 * 1024;

  /** Matches request callbackId */
  public String callbackId;

  /** Which phase this response is for: 1=BEFORE, 2=AFTER */
  public byte phase;

  /** Phase 1 (BEFORE phase of AROUND, or standalone BEFORE) */
  public Obj[] mutatedArgs;

  /** Proceed control (AROUND only, Phase 1 only) */
  public boolean shouldProceed;

  /** Phase 2 (AFTER phase of AROUND, or standalone AFTER) */
  public boolean overrideReturn;

  public Obj newReturnValue;

  public int newReturnRef;

  /** Both phases: exception throwing */
  public boolean throwException;

  public RaisedThrowable exception;

  /** Default constructor */
  public InterceptCallbackResponseMessage() {
    init();
  }

  private static final Obj[] _zeroMutatedArgs = new Obj[0];

  /** Colfer zero values. */
  private void init() {
    callbackId = "";
    mutatedArgs = _zeroMutatedArgs;
  }

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(InterceptCallbackResponseMessage.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax}
     *     or {@link #colferListMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public InterceptCallbackResponseMessage next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            InterceptCallbackResponseMessage o = new InterceptCallbackResponseMessage();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf =
                new byte
                    [Math.min(InterceptCallbackResponseMessage.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n = 1L + 6 + (long) this.callbackId.length() * 3 + 2 + 6 + 1 + 1 + 5 + 1;
    for (Obj o : this.mutatedArgs) {
      if (o == null) n++;
      else n += o.marshalFit();
    }
    if (this.newReturnValue != null) n += 1 + (long) this.newReturnValue.marshalFit();
    if (this.exception != null) n += 1 + (long) this.exception.marshalFit();
    if (n < 0 || n > (long) InterceptCallbackResponseMessage.colferSizeMax)
      return InterceptCallbackResponseMessage.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object. All {@code null} elements in {@link #mutatedArgs} will be replaced with
   * a {@code new} value.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax}
   *     or {@link #colferListMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object. All {@code null} elements in {@link #mutatedArgs} will be replaced with
   * a {@code new} value.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax}
   *     or {@link #colferListMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (!this.callbackId.isEmpty()) {
        buf[i++] = (byte) 0;
        int start = ++i;

        String s = this.callbackId;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InterceptCallbackResponseMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.callbackId size %d exceeds %d UTF-8 bytes",
                  size, InterceptCallbackResponseMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.phase != 0) {
        buf[i++] = (byte) 1;
        buf[i++] = this.phase;
      }

      if (this.mutatedArgs.length != 0) {
        buf[i++] = (byte) 2;
        Obj[] a = this.mutatedArgs;

        int x = a.length;
        if (x > InterceptCallbackResponseMessage.colferListMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.mutatedArgs length %d exceeds %d elements",
                  x, InterceptCallbackResponseMessage.colferListMax));
        while (x > 0x7f) {
          buf[i++] = (byte) (x | 0x80);
          x >>>= 7;
        }
        buf[i++] = (byte) x;

        for (int ai = 0; ai < a.length; ai++) {
          Obj o = a[ai];
          if (o == null) {
            o = new Obj();
            a[ai] = o;
          }
          i = o.marshal(buf, i);
        }
      }

      if (this.shouldProceed) {
        buf[i++] = (byte) 3;
      }

      if (this.overrideReturn) {
        buf[i++] = (byte) 4;
      }

      if (this.newReturnValue != null) {
        buf[i++] = (byte) 5;
        i = this.newReturnValue.marshal(buf, i);
      }

      if (this.newReturnRef != 0) {
        int x = this.newReturnRef;
        if ((x & ~((1 << 21) - 1)) != 0) {
          buf[i++] = (byte) (6 | 0x80);
          buf[i++] = (byte) (x >>> 24);
          buf[i++] = (byte) (x >>> 16);
          buf[i++] = (byte) (x >>> 8);
        } else {
          buf[i++] = (byte) 6;
          while (x > 0x7f) {
            buf[i++] = (byte) (x | 0x80);
            x >>>= 7;
          }
        }
        buf[i++] = (byte) x;
      }

      if (this.throwException) {
        buf[i++] = (byte) 7;
      }

      if (this.exception != null) {
        buf[i++] = (byte) 8;
        i = this.exception.marshal(buf, i);
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > InterceptCallbackResponseMessage.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage exceeds %d bytes",
                InterceptCallbackResponseMessage.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or
   *     {@link #colferListMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or
   *     {@link #colferListMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InterceptCallbackResponseMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.callbackId size %d exceeds %d UTF-8 bytes",
                  size, InterceptCallbackResponseMessage.colferSizeMax));

        int start = i;
        i += size;
        this.callbackId = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        this.phase = buf[i++];
        header = buf[i++];
      }

      if (header == (byte) 2) {
        int length = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          length |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (length < 0 || length > InterceptCallbackResponseMessage.colferListMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.mutatedArgs length %d exceeds %d elements",
                  length, InterceptCallbackResponseMessage.colferListMax));

        Obj[] a = new Obj[length];
        for (int ai = 0; ai < length; ai++) {
          Obj o = new Obj();
          i = o.unmarshal(buf, i, end);
          a[ai] = o;
        }
        this.mutatedArgs = a;
        header = buf[i++];
      }

      if (header == (byte) 3) {
        this.shouldProceed = true;
        header = buf[i++];
      }

      if (header == (byte) 4) {
        this.overrideReturn = true;
        header = buf[i++];
      }

      if (header == (byte) 5) {
        this.newReturnValue = new Obj();
        i = this.newReturnValue.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 6) {
        int x = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          x |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        this.newReturnRef = x;
        header = buf[i++];
      } else if (header == (byte) (6 | 0x80)) {
        this.newReturnRef =
            (buf[i++] & 0xff) << 24
                | (buf[i++] & 0xff) << 16
                | (buf[i++] & 0xff) << 8
                | (buf[i++] & 0xff);
        header = buf[i++];
      }

      if (header == (byte) 7) {
        this.throwException = true;
        header = buf[i++];
      }

      if (header == (byte) 8) {
        this.exception = new RaisedThrowable();
        i = this.exception.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < InterceptCallbackResponseMessage.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > InterceptCallbackResponseMessage.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage exceeds %d bytes",
                InterceptCallbackResponseMessage.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 9L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.callbackId.
   *
   * @return the value.
   */
  public String getCallbackId() {
    return this.callbackId;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.callbackId.
   *
   * @param value the replacement.
   */
  public void setCallbackId(String value) {
    this.callbackId = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.callbackId.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withCallbackId(String value) {
    this.callbackId = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.phase.
   *
   * @return the value.
   */
  public byte getPhase() {
    return this.phase;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.phase.
   *
   * @param value the replacement.
   */
  public void setPhase(byte value) {
    this.phase = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.phase.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withPhase(byte value) {
    this.phase = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.mutatedArgs.
   *
   * @return the value.
   */
  public Obj[] getMutatedArgs() {
    return this.mutatedArgs;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.mutatedArgs.
   *
   * @param value the replacement.
   */
  public void setMutatedArgs(Obj[] value) {
    this.mutatedArgs = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.mutatedArgs.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withMutatedArgs(Obj[] value) {
    this.mutatedArgs = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.shouldProceed.
   *
   * @return the value.
   */
  public boolean getShouldProceed() {
    return this.shouldProceed;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.shouldProceed.
   *
   * @param value the replacement.
   */
  public void setShouldProceed(boolean value) {
    this.shouldProceed = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.shouldProceed.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withShouldProceed(boolean value) {
    this.shouldProceed = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.overrideReturn.
   *
   * @return the value.
   */
  public boolean getOverrideReturn() {
    return this.overrideReturn;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.overrideReturn.
   *
   * @param value the replacement.
   */
  public void setOverrideReturn(boolean value) {
    this.overrideReturn = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.overrideReturn.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withOverrideReturn(boolean value) {
    this.overrideReturn = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.newReturnValue.
   *
   * @return the value.
   */
  public Obj getNewReturnValue() {
    return this.newReturnValue;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.newReturnValue.
   *
   * @param value the replacement.
   */
  public void setNewReturnValue(Obj value) {
    this.newReturnValue = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.newReturnValue.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withNewReturnValue(Obj value) {
    this.newReturnValue = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.newReturnRef.
   *
   * @return the value.
   */
  public int getNewReturnRef() {
    return this.newReturnRef;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.newReturnRef.
   *
   * @param value the replacement.
   */
  public void setNewReturnRef(int value) {
    this.newReturnRef = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.newReturnRef.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withNewReturnRef(int value) {
    this.newReturnRef = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.throwException.
   *
   * @return the value.
   */
  public boolean getThrowException() {
    return this.throwException;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.throwException.
   *
   * @param value the replacement.
   */
  public void setThrowException(boolean value) {
    this.throwException = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.throwException.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withThrowException(boolean value) {
    this.throwException = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.exception.
   *
   * @return the value.
   */
  public RaisedThrowable getException() {
    return this.exception;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.exception.
   *
   * @param value the replacement.
   */
  public void setException(RaisedThrowable value) {
    this.exception = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptCallbackResponseMessage.exception.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptCallbackResponseMessage withException(RaisedThrowable value) {
    this.exception = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.callbackId != null) h = 31 * h + this.callbackId.hashCode();
    h = 31 * h + (this.phase & 0xff);
    for (Obj o : this.mutatedArgs) h = 31 * h + (o == null ? 0 : o.hashCode());
    h = 31 * h + (this.shouldProceed ? 1231 : 1237);
    h = 31 * h + (this.overrideReturn ? 1231 : 1237);
    if (this.newReturnValue != null) h = 31 * h + this.newReturnValue.hashCode();
    h = 31 * h + this.newReturnRef;
    h = 31 * h + (this.throwException ? 1231 : 1237);
    if (this.exception != null) h = 31 * h + this.exception.hashCode();
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof InterceptCallbackResponseMessage
        && equals((InterceptCallbackResponseMessage) o);
  }

  public final boolean equals(InterceptCallbackResponseMessage o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.callbackId == null ? o.callbackId == null : this.callbackId.equals(o.callbackId))
        && this.phase == o.phase
        && java.util.Arrays.equals(this.mutatedArgs, o.mutatedArgs)
        && this.shouldProceed == o.shouldProceed
        && this.overrideReturn == o.overrideReturn
        && (this.newReturnValue == null
            ? o.newReturnValue == null
            : this.newReturnValue.equals(o.newReturnValue))
        && this.newReturnRef == o.newReturnRef
        && this.throwException == o.throwException
        && (this.exception == null ? o.exception == null : this.exception.equals(o.exception));
  }

  @Override
  public InterceptCallbackResponseMessage fromJson(JsonObject json) throws JsonParseException {
    try {
      if (json.has("callbackId")) {
        this.callbackId = json.get("callbackId").getAsString();
      }

      if (json.has("phase")) {
        this.phase = json.get("phase").getAsByte();
      }

      if (json.has("mutatedArgs")) {
        JsonArray jsonArray = json.getAsJsonArray("mutatedArgs");
        this.mutatedArgs = new Obj[jsonArray.size()];
        for (int i = 0; i < jsonArray.size(); i++) {
          JsonObject jsonObj = jsonArray.get(i).getAsJsonObject();
          this.mutatedArgs[i] = new Obj().fromJson(jsonObj);
        }
      }
      if (json.has("shouldProceed")) {
        this.shouldProceed = json.get("shouldProceed").getAsBoolean();
      }

      if (json.has("overrideReturn")) {
        this.overrideReturn = json.get("overrideReturn").getAsBoolean();
      }

      if (json.has("newReturnValue")) {
        JsonObject jsonObj = json.getAsJsonObject("newReturnValue");
        this.newReturnValue = new Obj().fromJson(jsonObj);
      }

      if (json.has("newReturnRef")) {
        this.newReturnRef = json.get("newReturnRef").getAsInt();
      }

      if (json.has("throwException")) {
        this.throwException = json.get("throwException").getAsBoolean();
      }

      if (json.has("exception")) {
        JsonObject jsonObj = json.getAsJsonObject("exception");
        this.exception = new RaisedThrowable().fromJson(jsonObj);
      }

    } catch (Exception e) {
      throw new JsonParseException("Error deserializing json object: " + e.getMessage(), e);
    }
    return this;
  }

  /**
   * Resets this Colfer message to its zero state for reuse on the hot path. Calls init(), then
   * zeros primitives and nulls nested messages.
   */
  public void reset() {
    init();
    this.phase = (byte) 0;
    this.shouldProceed = false;
    this.overrideReturn = false;
    this.newReturnValue = null;
    this.newReturnRef = 0;
    this.throwException = false;
    this.exception = null;
  }
}
