/*
 * Copyright (C) 2026 Quasient Inc. <https://www.quasient.com>
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in the file LICENSE and at https://mariadb.com/bsl11
 *
 * Change Date: 2030-10-01
 * Change License: Apache 2.0
 */
package io.quasient.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, meta.colf, primitives.colf, values.colf,
// wrappers.colf and calls.colf.

import static java.lang.String.format;

import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class InterceptMessage implements Serializable, io.quasient.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  public String peerUuid;

  public String messageId;

  public byte interceptType;

  public String clazz;

  public InterceptableField field;

  public InterceptableMethod method;

  public String callbackClass;

  public String callbackMethod;

  public boolean forceImmediate;

  public byte exceptionPropagationPolicy;

  public byte checkedExceptionPolicy;

  /** Default constructor */
  public InterceptMessage() {
    init();
  }

  /** Colfer zero values. */
  private void init() {
    peerUuid = "";
    messageId = "";
    clazz = "";
    callbackClass = "";
    callbackMethod = "";
  }

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(InterceptMessage.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public InterceptMessage next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            InterceptMessage o = new InterceptMessage();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(InterceptMessage.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n =
        1L
            + 6
            + (long) this.peerUuid.length() * 3
            + 6
            + (long) this.messageId.length() * 3
            + 2
            + 6
            + (long) this.clazz.length() * 3
            + 6
            + (long) this.callbackClass.length() * 3
            + 6
            + (long) this.callbackMethod.length() * 3
            + 1
            + 2
            + 2;
    if (this.field != null) n += 1 + (long) this.field.marshalFit();
    if (this.method != null) n += 1 + (long) this.method.marshalFit();
    if (n < 0 || n > (long) InterceptMessage.colferSizeMax) return InterceptMessage.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (!this.peerUuid.isEmpty()) {
        buf[i++] = (byte) 0;
        int start = ++i;

        String s = this.peerUuid;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InterceptMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.peerUuid size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (!this.messageId.isEmpty()) {
        buf[i++] = (byte) 1;
        int start = ++i;

        String s = this.messageId;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InterceptMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.messageId size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.interceptType != 0) {
        buf[i++] = (byte) 2;
        buf[i++] = this.interceptType;
      }

      if (!this.clazz.isEmpty()) {
        buf[i++] = (byte) 3;
        int start = ++i;

        String s = this.clazz;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InterceptMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.clazz size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.field != null) {
        buf[i++] = (byte) 4;
        i = this.field.marshal(buf, i);
      }

      if (this.method != null) {
        buf[i++] = (byte) 5;
        i = this.method.marshal(buf, i);
      }

      if (!this.callbackClass.isEmpty()) {
        buf[i++] = (byte) 6;
        int start = ++i;

        String s = this.callbackClass;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InterceptMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.callbackClass size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (!this.callbackMethod.isEmpty()) {
        buf[i++] = (byte) 7;
        int start = ++i;

        String s = this.callbackMethod;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InterceptMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.callbackMethod size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.forceImmediate) {
        buf[i++] = (byte) 8;
      }

      if (this.exceptionPropagationPolicy != 0) {
        buf[i++] = (byte) 9;
        buf[i++] = this.exceptionPropagationPolicy;
      }

      if (this.checkedExceptionPolicy != 0) {
        buf[i++] = (byte) 10;
        buf[i++] = this.checkedExceptionPolicy;
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > InterceptMessage.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InterceptMessage exceeds %d bytes",
                InterceptMessage.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InterceptMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.peerUuid size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int start = i;
        i += size;
        this.peerUuid = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InterceptMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.messageId size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int start = i;
        i += size;
        this.messageId = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 2) {
        this.interceptType = buf[i++];
        header = buf[i++];
      }

      if (header == (byte) 3) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InterceptMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.clazz size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int start = i;
        i += size;
        this.clazz = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 4) {
        this.field = new InterceptableField();
        i = this.field.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 5) {
        this.method = new InterceptableMethod();
        i = this.method.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 6) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InterceptMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.callbackClass size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int start = i;
        i += size;
        this.callbackClass = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 7) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InterceptMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptMessage.callbackMethod size %d exceeds %d UTF-8 bytes",
                  size, InterceptMessage.colferSizeMax));

        int start = i;
        i += size;
        this.callbackMethod = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 8) {
        this.forceImmediate = true;
        header = buf[i++];
      }

      if (header == (byte) 9) {
        this.exceptionPropagationPolicy = buf[i++];
        header = buf[i++];
      }

      if (header == (byte) 10) {
        this.checkedExceptionPolicy = buf[i++];
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < InterceptMessage.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > InterceptMessage.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InterceptMessage exceeds %d bytes",
                InterceptMessage.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 11L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.peerUuid.
   *
   * @return the value.
   */
  public String getPeerUuid() {
    return this.peerUuid;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.peerUuid.
   *
   * @param value the replacement.
   */
  public void setPeerUuid(String value) {
    this.peerUuid = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.peerUuid.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withPeerUuid(String value) {
    this.peerUuid = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.messageId.
   *
   * @return the value.
   */
  public String getMessageId() {
    return this.messageId;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.messageId.
   *
   * @param value the replacement.
   */
  public void setMessageId(String value) {
    this.messageId = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.messageId.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withMessageId(String value) {
    this.messageId = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.interceptType.
   *
   * @return the value.
   */
  public byte getInterceptType() {
    return this.interceptType;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.interceptType.
   *
   * @param value the replacement.
   */
  public void setInterceptType(byte value) {
    this.interceptType = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.interceptType.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withInterceptType(byte value) {
    this.interceptType = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.clazz.
   *
   * @return the value.
   */
  public String getClazz() {
    return this.clazz;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.clazz.
   *
   * @param value the replacement.
   */
  public void setClazz(String value) {
    this.clazz = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.clazz.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withClazz(String value) {
    this.clazz = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.field.
   *
   * @return the value.
   */
  public InterceptableField getField() {
    return this.field;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.field.
   *
   * @param value the replacement.
   */
  public void setField(InterceptableField value) {
    this.field = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.field.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withField(InterceptableField value) {
    this.field = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.method.
   *
   * @return the value.
   */
  public InterceptableMethod getMethod() {
    return this.method;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.method.
   *
   * @param value the replacement.
   */
  public void setMethod(InterceptableMethod value) {
    this.method = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.method.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withMethod(InterceptableMethod value) {
    this.method = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.callbackClass.
   *
   * @return the value.
   */
  public String getCallbackClass() {
    return this.callbackClass;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.callbackClass.
   *
   * @param value the replacement.
   */
  public void setCallbackClass(String value) {
    this.callbackClass = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.callbackClass.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withCallbackClass(String value) {
    this.callbackClass = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.callbackMethod.
   *
   * @return the value.
   */
  public String getCallbackMethod() {
    return this.callbackMethod;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.callbackMethod.
   *
   * @param value the replacement.
   */
  public void setCallbackMethod(String value) {
    this.callbackMethod = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.callbackMethod.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withCallbackMethod(String value) {
    this.callbackMethod = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.forceImmediate.
   *
   * @return the value.
   */
  public boolean getForceImmediate() {
    return this.forceImmediate;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.forceImmediate.
   *
   * @param value the replacement.
   */
  public void setForceImmediate(boolean value) {
    this.forceImmediate = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.forceImmediate.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withForceImmediate(boolean value) {
    this.forceImmediate = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.exceptionPropagationPolicy.
   *
   * @return the value.
   */
  public byte getExceptionPropagationPolicy() {
    return this.exceptionPropagationPolicy;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.exceptionPropagationPolicy.
   *
   * @param value the replacement.
   */
  public void setExceptionPropagationPolicy(byte value) {
    this.exceptionPropagationPolicy = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.exceptionPropagationPolicy.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withExceptionPropagationPolicy(byte value) {
    this.exceptionPropagationPolicy = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptMessage.checkedExceptionPolicy.
   *
   * @return the value.
   */
  public byte getCheckedExceptionPolicy() {
    return this.checkedExceptionPolicy;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.checkedExceptionPolicy.
   *
   * @param value the replacement.
   */
  public void setCheckedExceptionPolicy(byte value) {
    this.checkedExceptionPolicy = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptMessage.checkedExceptionPolicy.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptMessage withCheckedExceptionPolicy(byte value) {
    this.checkedExceptionPolicy = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.peerUuid != null) h = 31 * h + this.peerUuid.hashCode();
    if (this.messageId != null) h = 31 * h + this.messageId.hashCode();
    h = 31 * h + (this.interceptType & 0xff);
    if (this.clazz != null) h = 31 * h + this.clazz.hashCode();
    if (this.field != null) h = 31 * h + this.field.hashCode();
    if (this.method != null) h = 31 * h + this.method.hashCode();
    if (this.callbackClass != null) h = 31 * h + this.callbackClass.hashCode();
    if (this.callbackMethod != null) h = 31 * h + this.callbackMethod.hashCode();
    h = 31 * h + (this.forceImmediate ? 1231 : 1237);
    h = 31 * h + (this.exceptionPropagationPolicy & 0xff);
    h = 31 * h + (this.checkedExceptionPolicy & 0xff);
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof InterceptMessage && equals((InterceptMessage) o);
  }

  public final boolean equals(InterceptMessage o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.peerUuid == null ? o.peerUuid == null : this.peerUuid.equals(o.peerUuid))
        && (this.messageId == null ? o.messageId == null : this.messageId.equals(o.messageId))
        && this.interceptType == o.interceptType
        && (this.clazz == null ? o.clazz == null : this.clazz.equals(o.clazz))
        && (this.field == null ? o.field == null : this.field.equals(o.field))
        && (this.method == null ? o.method == null : this.method.equals(o.method))
        && (this.callbackClass == null
            ? o.callbackClass == null
            : this.callbackClass.equals(o.callbackClass))
        && (this.callbackMethod == null
            ? o.callbackMethod == null
            : this.callbackMethod.equals(o.callbackMethod))
        && this.forceImmediate == o.forceImmediate
        && this.exceptionPropagationPolicy == o.exceptionPropagationPolicy
        && this.checkedExceptionPolicy == o.checkedExceptionPolicy;
  }

  @Override
  public InterceptMessage fromJson(JsonObject json) throws JsonParseException {
    try {
      if (json.has("peerUuid")) {
        this.peerUuid = json.get("peerUuid").getAsString();
      }

      if (json.has("messageId")) {
        this.messageId = json.get("messageId").getAsString();
      }

      if (json.has("interceptType")) {
        this.interceptType = json.get("interceptType").getAsByte();
      }

      if (json.has("clazz")) {
        this.clazz = json.get("clazz").getAsString();
      }

      if (json.has("field")) {
        JsonObject jsonObj = json.getAsJsonObject("field");
        this.field = new InterceptableField().fromJson(jsonObj);
      }

      if (json.has("method")) {
        JsonObject jsonObj = json.getAsJsonObject("method");
        this.method = new InterceptableMethod().fromJson(jsonObj);
      }

      if (json.has("callbackClass")) {
        this.callbackClass = json.get("callbackClass").getAsString();
      }

      if (json.has("callbackMethod")) {
        this.callbackMethod = json.get("callbackMethod").getAsString();
      }

      if (json.has("forceImmediate")) {
        this.forceImmediate = json.get("forceImmediate").getAsBoolean();
      }

      if (json.has("exceptionPropagationPolicy")) {
        this.exceptionPropagationPolicy = json.get("exceptionPropagationPolicy").getAsByte();
      }

      if (json.has("checkedExceptionPolicy")) {
        this.checkedExceptionPolicy = json.get("checkedExceptionPolicy").getAsByte();
      }

    } catch (Exception e) {
      throw new JsonParseException("Error deserializing json object: " + e.getMessage(), e);
    }
    return this;
  }

  /**
   * Resets this Colfer message to its zero state for reuse on the hot path. Calls init(), then
   * zeros primitives and nulls nested messages.
   */
  public void reset() {
    init();
    this.interceptType = (byte) 0;
    this.field = null;
    this.method = null;
    this.forceImmediate = false;
    this.exceptionPropagationPolicy = (byte) 0;
    this.checkedExceptionPolicy = (byte) 0;
  }
}
