/*
 * Copyright (C) 2026 Quasient Inc. <https://www.quasient.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quasient.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, meta.colf, primitives.colf, values.colf,
// wrappers.colf and calls.colf.

import static java.lang.String.format;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class InterceptableMethod implements Serializable, io.quasient.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  /** The upper limit for the number of elements in a list. */
  public static int colferListMax = 64 * 1024;

  public String name;

  public String[] parameterTypes;

  /** Default constructor */
  public InterceptableMethod() {
    init();
  }

  private static final String[] _zeroParameterTypes = new String[0];

  /** Colfer zero values. */
  private void init() {
    name = "";
    parameterTypes = _zeroParameterTypes;
  }

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(InterceptableMethod.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax}
     *     or {@link #colferListMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public InterceptableMethod next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            InterceptableMethod o = new InterceptableMethod();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(InterceptableMethod.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n = 1L + 6 + (long) this.name.length() * 3 + 6 + (long) this.parameterTypes.length * 6;
    for (String s : this.parameterTypes) if (s != null) n += (long) s.length() * 3;
    if (n < 0 || n > (long) InterceptableMethod.colferSizeMax)
      return InterceptableMethod.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object. All {@code null} elements in {@link #parameterTypes} will be replaced
   * with {@code ""}.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax}
   *     or {@link #colferListMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object. All {@code null} elements in {@link #parameterTypes} will be replaced
   * with {@code ""}.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax}
   *     or {@link #colferListMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (!this.name.isEmpty()) {
        buf[i++] = (byte) 0;
        int start = ++i;

        String s = this.name;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InterceptableMethod.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptableMethod.name size %d exceeds %d UTF-8 bytes",
                  size, InterceptableMethod.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.parameterTypes.length != 0) {
        buf[i++] = (byte) 1;
        String[] a = this.parameterTypes;

        int x = a.length;
        if (x > InterceptableMethod.colferListMax)
          throw new IllegalStateException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptableMethod.parameterTypes length %d exceeds %d elements",
                  x, InterceptableMethod.colferListMax));
        while (x > 0x7f) {
          buf[i++] = (byte) (x | 0x80);
          x >>>= 7;
        }
        buf[i++] = (byte) x;

        for (int ai = 0; ai < a.length; ai++) {
          String s = a[ai];
          if (s == null) {
            s = "";
            a[ai] = s;
          }

          int start = ++i;

          for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
            char c = s.charAt(sIndex);
            if (c < '\u0080') {
              buf[i++] = (byte) c;
            } else if (c < '\u0800') {
              buf[i++] = (byte) (192 | c >>> 6);
              buf[i++] = (byte) (128 | c & 63);
            } else if (c < '\ud800' || c > '\udfff') {
              buf[i++] = (byte) (224 | c >>> 12);
              buf[i++] = (byte) (128 | c >>> 6 & 63);
              buf[i++] = (byte) (128 | c & 63);
            } else {
              int cp = 0;
              if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
              if ((cp >= 1 << 16) && (cp < 1 << 21)) {
                buf[i++] = (byte) (240 | cp >>> 18);
                buf[i++] = (byte) (128 | cp >>> 12 & 63);
                buf[i++] = (byte) (128 | cp >>> 6 & 63);
                buf[i++] = (byte) (128 | cp & 63);
              } else buf[i++] = (byte) '?';
            }
          }
          int size = i - start;
          if (size > InterceptableMethod.colferSizeMax)
            throw new IllegalStateException(
                format(
                    "colfer: io.quasient.pal.messages/colfer.InterceptableMethod.parameterTypes[%d] size %d exceeds %d UTF-8 bytes",
                    ai, size, InterceptableMethod.colferSizeMax));

          int ii = start - 1;
          if (size > 0x7f) {
            i++;
            for (int y = size; y >= 1 << 14; y >>>= 7) i++;
            System.arraycopy(buf, start, buf, i - size, size);

            do {
              buf[ii++] = (byte) (size | 0x80);
              size >>>= 7;
            } while (size > 0x7f);
          }
          buf[ii] = (byte) size;
        }
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > InterceptableMethod.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InterceptableMethod exceeds %d bytes",
                InterceptableMethod.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or
   *     {@link #colferListMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or
   *     {@link #colferListMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InterceptableMethod.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptableMethod.name size %d exceeds %d UTF-8 bytes",
                  size, InterceptableMethod.colferSizeMax));

        int start = i;
        i += size;
        this.name = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        int length = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          length |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (length < 0 || length > InterceptableMethod.colferListMax)
          throw new SecurityException(
              format(
                  "colfer: io.quasient.pal.messages/colfer.InterceptableMethod.parameterTypes length %d exceeds %d elements",
                  length, InterceptableMethod.colferListMax));

        String[] a = new String[length];
        for (int ai = 0; ai < length; ai++) {
          int size = 0;
          for (int shift = 0; true; shift += 7) {
            byte b = buf[i++];
            size |= (b & 0x7f) << shift;
            if (shift == 28 || b >= 0) break;
          }
          if (size < 0 || size > InterceptableMethod.colferSizeMax)
            throw new SecurityException(
                format(
                    "colfer: io.quasient.pal.messages/colfer.InterceptableMethod.parameterTypes[%d] size %d exceeds %d UTF-8 bytes",
                    ai, size, InterceptableMethod.colferSizeMax));

          int start = i;
          i += size;
          a[ai] = new String(buf, start, size, StandardCharsets.UTF_8);
        }
        this.parameterTypes = a;
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < InterceptableMethod.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > InterceptableMethod.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: io.quasient.pal.messages/colfer.InterceptableMethod exceeds %d bytes",
                InterceptableMethod.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 2L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptableMethod.name.
   *
   * @return the value.
   */
  public String getName() {
    return this.name;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptableMethod.name.
   *
   * @param value the replacement.
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptableMethod.name.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptableMethod withName(String value) {
    this.name = value;
    return this;
  }

  /**
   * Gets io.quasient.pal.messages/colfer.InterceptableMethod.parameterTypes.
   *
   * @return the value.
   */
  public String[] getParameterTypes() {
    return this.parameterTypes;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptableMethod.parameterTypes.
   *
   * @param value the replacement.
   */
  public void setParameterTypes(String[] value) {
    this.parameterTypes = value;
  }

  /**
   * Sets io.quasient.pal.messages/colfer.InterceptableMethod.parameterTypes.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InterceptableMethod withParameterTypes(String[] value) {
    this.parameterTypes = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.name != null) h = 31 * h + this.name.hashCode();
    for (String o : this.parameterTypes) h = 31 * h + (o == null ? 0 : o.hashCode());
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof InterceptableMethod && equals((InterceptableMethod) o);
  }

  public final boolean equals(InterceptableMethod o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.name == null ? o.name == null : this.name.equals(o.name))
        && java.util.Arrays.equals(this.parameterTypes, o.parameterTypes);
  }

  @Override
  public InterceptableMethod fromJson(JsonObject json) throws JsonParseException {
    try {
      if (json.has("name")) {
        this.name = json.get("name").getAsString();
      }

      if (json.has("parameterTypes")) {
        JsonArray jsonArray = json.getAsJsonArray("parameterTypes");
        this.parameterTypes = new String[jsonArray.size()];
        for (int i = 0; i < jsonArray.size(); i++) {
          this.parameterTypes[i] = jsonArray.get(i).getAsString();
        }
      }
    } catch (Exception e) {
      throw new JsonParseException("Error deserializing json object: " + e.getMessage(), e);
    }
    return this;
  }

  /**
   * Resets this Colfer message to its zero state for reuse on the hot path. Calls init(), then
   * zeros primitives and nulls nested messages.
   */
  public void reset() {
    init();
  }
}
