// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: values.proto

package com.ittera.cometa.concentrator.messages.protobuf.data;

public final class Values {
  private Values() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReturnValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.protobuf.data.ReturnValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool isVoid = 1 [default = false];</code>
     */
    boolean hasIsVoid();
    /**
     * <code>optional bool isVoid = 1 [default = false];</code>
     */
    boolean getIsVoid();

    /**
     * <code>optional bool isClass = 2 [default = false];</code>
     */
    boolean hasIsClass();
    /**
     * <code>optional bool isClass = 2 [default = false];</code>
     */
    boolean getIsClass();

    /**
     * <code>optional .messages.protobuf.data.Object object = 3;</code>
     */
    boolean hasObject();
    /**
     * <code>optional .messages.protobuf.data.Object object = 3;</code>
     */
    com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object getObject();
    /**
     * <code>optional .messages.protobuf.data.Object object = 3;</code>
     */
    com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ObjectOrBuilder getObjectOrBuilder();

    /**
     * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
     */
    boolean hasClazz();
    /**
     * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
     */
    com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class getClazz();
    /**
     * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
     */
    com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ClassOrBuilder getClazzOrBuilder();
  }
  /**
   * Protobuf type {@code messages.protobuf.data.ReturnValue}
   */
  public  static final class ReturnValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.protobuf.data.ReturnValue)
      ReturnValueOrBuilder {
    // Use ReturnValue.newBuilder() to construct.
    private ReturnValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReturnValue() {
      isVoid_ = false;
      isClass_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReturnValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isVoid_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isClass_ = input.readBool();
              break;
            }
            case 26: {
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = object_.toBuilder();
              }
              object_ = input.readMessage(com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(object_);
                object_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = clazz_.toBuilder();
              }
              clazz_ = input.readMessage(com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clazz_);
                clazz_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ittera.cometa.concentrator.messages.protobuf.data.Values.internal_static_messages_protobuf_data_ReturnValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ittera.cometa.concentrator.messages.protobuf.data.Values.internal_static_messages_protobuf_data_ReturnValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue.class, com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue.Builder.class);
    }

    private int bitField0_;
    public static final int ISVOID_FIELD_NUMBER = 1;
    private boolean isVoid_;
    /**
     * <code>optional bool isVoid = 1 [default = false];</code>
     */
    public boolean hasIsVoid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool isVoid = 1 [default = false];</code>
     */
    public boolean getIsVoid() {
      return isVoid_;
    }

    public static final int ISCLASS_FIELD_NUMBER = 2;
    private boolean isClass_;
    /**
     * <code>optional bool isClass = 2 [default = false];</code>
     */
    public boolean hasIsClass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isClass = 2 [default = false];</code>
     */
    public boolean getIsClass() {
      return isClass_;
    }

    public static final int OBJECT_FIELD_NUMBER = 3;
    private com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object object_;
    /**
     * <code>optional .messages.protobuf.data.Object object = 3;</code>
     */
    public boolean hasObject() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .messages.protobuf.data.Object object = 3;</code>
     */
    public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object getObject() {
      return object_ == null ? com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.getDefaultInstance() : object_;
    }
    /**
     * <code>optional .messages.protobuf.data.Object object = 3;</code>
     */
    public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ObjectOrBuilder getObjectOrBuilder() {
      return object_ == null ? com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.getDefaultInstance() : object_;
    }

    public static final int CLAZZ_FIELD_NUMBER = 4;
    private com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class clazz_;
    /**
     * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
     */
    public boolean hasClazz() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
     */
    public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class getClazz() {
      return clazz_ == null ? com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.getDefaultInstance() : clazz_;
    }
    /**
     * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
     */
    public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ClassOrBuilder getClazzOrBuilder() {
      return clazz_ == null ? com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.getDefaultInstance() : clazz_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasObject()) {
        if (!getObject().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isVoid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isClass_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getObject());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getClazz());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isVoid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isClass_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getObject());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getClazz());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue)) {
        return super.equals(obj);
      }
      com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue other = (com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue) obj;

      boolean result = true;
      result = result && (hasIsVoid() == other.hasIsVoid());
      if (hasIsVoid()) {
        result = result && (getIsVoid()
            == other.getIsVoid());
      }
      result = result && (hasIsClass() == other.hasIsClass());
      if (hasIsClass()) {
        result = result && (getIsClass()
            == other.getIsClass());
      }
      result = result && (hasObject() == other.hasObject());
      if (hasObject()) {
        result = result && getObject()
            .equals(other.getObject());
      }
      result = result && (hasClazz() == other.hasClazz());
      if (hasClazz()) {
        result = result && getClazz()
            .equals(other.getClazz());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsVoid()) {
        hash = (37 * hash) + ISVOID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsVoid());
      }
      if (hasIsClass()) {
        hash = (37 * hash) + ISCLASS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsClass());
      }
      if (hasObject()) {
        hash = (37 * hash) + OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getObject().hashCode();
      }
      if (hasClazz()) {
        hash = (37 * hash) + CLAZZ_FIELD_NUMBER;
        hash = (53 * hash) + getClazz().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.protobuf.data.ReturnValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.protobuf.data.ReturnValue)
        com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ittera.cometa.concentrator.messages.protobuf.data.Values.internal_static_messages_protobuf_data_ReturnValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ittera.cometa.concentrator.messages.protobuf.data.Values.internal_static_messages_protobuf_data_ReturnValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue.class, com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue.Builder.class);
      }

      // Construct using com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getObjectFieldBuilder();
          getClazzFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        isVoid_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        isClass_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (objectBuilder_ == null) {
          object_ = null;
        } else {
          objectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (clazzBuilder_ == null) {
          clazz_ = null;
        } else {
          clazzBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ittera.cometa.concentrator.messages.protobuf.data.Values.internal_static_messages_protobuf_data_ReturnValue_descriptor;
      }

      public com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue getDefaultInstanceForType() {
        return com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue.getDefaultInstance();
      }

      public com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue build() {
        com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue buildPartial() {
        com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue result = new com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isVoid_ = isVoid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isClass_ = isClass_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (objectBuilder_ == null) {
          result.object_ = object_;
        } else {
          result.object_ = objectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (clazzBuilder_ == null) {
          result.clazz_ = clazz_;
        } else {
          result.clazz_ = clazzBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue) {
          return mergeFrom((com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue other) {
        if (other == com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue.getDefaultInstance()) return this;
        if (other.hasIsVoid()) {
          setIsVoid(other.getIsVoid());
        }
        if (other.hasIsClass()) {
          setIsClass(other.getIsClass());
        }
        if (other.hasObject()) {
          mergeObject(other.getObject());
        }
        if (other.hasClazz()) {
          mergeClazz(other.getClazz());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasObject()) {
          if (!getObject().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isVoid_ ;
      /**
       * <code>optional bool isVoid = 1 [default = false];</code>
       */
      public boolean hasIsVoid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool isVoid = 1 [default = false];</code>
       */
      public boolean getIsVoid() {
        return isVoid_;
      }
      /**
       * <code>optional bool isVoid = 1 [default = false];</code>
       */
      public Builder setIsVoid(boolean value) {
        bitField0_ |= 0x00000001;
        isVoid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isVoid = 1 [default = false];</code>
       */
      public Builder clearIsVoid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isVoid_ = false;
        onChanged();
        return this;
      }

      private boolean isClass_ ;
      /**
       * <code>optional bool isClass = 2 [default = false];</code>
       */
      public boolean hasIsClass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isClass = 2 [default = false];</code>
       */
      public boolean getIsClass() {
        return isClass_;
      }
      /**
       * <code>optional bool isClass = 2 [default = false];</code>
       */
      public Builder setIsClass(boolean value) {
        bitField0_ |= 0x00000002;
        isClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isClass = 2 [default = false];</code>
       */
      public Builder clearIsClass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isClass_ = false;
        onChanged();
        return this;
      }

      private com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object object_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.Builder, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ObjectOrBuilder> objectBuilder_;
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public boolean hasObject() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object getObject() {
        if (objectBuilder_ == null) {
          return object_ == null ? com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.getDefaultInstance() : object_;
        } else {
          return objectBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public Builder setObject(com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object value) {
        if (objectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          object_ = value;
          onChanged();
        } else {
          objectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public Builder setObject(
          com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.Builder builderForValue) {
        if (objectBuilder_ == null) {
          object_ = builderForValue.build();
          onChanged();
        } else {
          objectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public Builder mergeObject(com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object value) {
        if (objectBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              object_ != null &&
              object_ != com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.getDefaultInstance()) {
            object_ =
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.newBuilder(object_).mergeFrom(value).buildPartial();
          } else {
            object_ = value;
          }
          onChanged();
        } else {
          objectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public Builder clearObject() {
        if (objectBuilder_ == null) {
          object_ = null;
          onChanged();
        } else {
          objectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.Builder getObjectBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ObjectOrBuilder getObjectOrBuilder() {
        if (objectBuilder_ != null) {
          return objectBuilder_.getMessageOrBuilder();
        } else {
          return object_ == null ?
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.getDefaultInstance() : object_;
        }
      }
      /**
       * <code>optional .messages.protobuf.data.Object object = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.Builder, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ObjectOrBuilder> 
          getObjectFieldBuilder() {
        if (objectBuilder_ == null) {
          objectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Object.Builder, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ObjectOrBuilder>(
                  getObject(),
                  getParentForChildren(),
                  isClean());
          object_ = null;
        }
        return objectBuilder_;
      }

      private com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class clazz_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.Builder, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ClassOrBuilder> clazzBuilder_;
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public boolean hasClazz() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class getClazz() {
        if (clazzBuilder_ == null) {
          return clazz_ == null ? com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.getDefaultInstance() : clazz_;
        } else {
          return clazzBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public Builder setClazz(com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class value) {
        if (clazzBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clazz_ = value;
          onChanged();
        } else {
          clazzBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public Builder setClazz(
          com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.Builder builderForValue) {
        if (clazzBuilder_ == null) {
          clazz_ = builderForValue.build();
          onChanged();
        } else {
          clazzBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public Builder mergeClazz(com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class value) {
        if (clazzBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              clazz_ != null &&
              clazz_ != com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.getDefaultInstance()) {
            clazz_ =
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.newBuilder(clazz_).mergeFrom(value).buildPartial();
          } else {
            clazz_ = value;
          }
          onChanged();
        } else {
          clazzBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public Builder clearClazz() {
        if (clazzBuilder_ == null) {
          clazz_ = null;
          onChanged();
        } else {
          clazzBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.Builder getClazzBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getClazzFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      public com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ClassOrBuilder getClazzOrBuilder() {
        if (clazzBuilder_ != null) {
          return clazzBuilder_.getMessageOrBuilder();
        } else {
          return clazz_ == null ?
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.getDefaultInstance() : clazz_;
        }
      }
      /**
       * <code>optional .messages.protobuf.data.Class clazz = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.Builder, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ClassOrBuilder> 
          getClazzFieldBuilder() {
        if (clazzBuilder_ == null) {
          clazzBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.Class.Builder, com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.ClassOrBuilder>(
                  getClazz(),
                  getParentForChildren(),
                  isClean());
          clazz_ = null;
        }
        return clazzBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.protobuf.data.ReturnValue)
    }

    // @@protoc_insertion_point(class_scope:messages.protobuf.data.ReturnValue)
    private static final com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue();
    }

    public static com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReturnValue>
        PARSER = new com.google.protobuf.AbstractParser<ReturnValue>() {
      public ReturnValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReturnValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReturnValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReturnValue> getParserForType() {
      return PARSER;
    }

    public com.ittera.cometa.concentrator.messages.protobuf.data.Values.ReturnValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_protobuf_data_ReturnValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_protobuf_data_ReturnValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014values.proto\022\026messages.protobuf.data\032\020" +
      "primitives.proto\"\232\001\n\013ReturnValue\022\025\n\006isVo" +
      "id\030\001 \001(\010:\005false\022\026\n\007isClass\030\002 \001(\010:\005false\022" +
      ".\n\006object\030\003 \001(\0132\036.messages.protobuf.data" +
      ".Object\022,\n\005clazz\030\004 \001(\0132\035.messages.protob" +
      "uf.data.ClassBA\n5com.ittera.cometa.conce" +
      "ntrator.messages.protobuf.dataB\006ValuesH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.getDescriptor(),
        }, assigner);
    internal_static_messages_protobuf_data_ReturnValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_protobuf_data_ReturnValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_protobuf_data_ReturnValue_descriptor,
        new java.lang.String[] { "IsVoid", "IsClass", "Object", "Clazz", });
    com.ittera.cometa.concentrator.messages.protobuf.data.Primitives.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
