#
# Copyright (C) 2025 Quasient Inc. <https://www.quasient.com>
#
# Use of this software is governed by the Business Source License 1.1
# included in the file LICENSE and at https://mariadb.com/bsl11
#
# Change Date: 2029-10-01
# Change License: Apache 2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.16
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/etcd"]
          args:
            - --name=default
            - --data-dir=/var/lib/etcd         # ⇦ will be a PVC
            - --initial-advertise-peer-urls=http://etcd:2380
            - --listen-peer-urls=http://0.0.0.0:2380
            - --advertise-client-urls=http://etcd:2379
            - --listen-client-urls=http://0.0.0.0:2379
            - --initial-cluster=default=http://etcd:2380
          ports:
            - containerPort: 2379   # client
            - containerPort: 2380   # peer
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib/etcd         # must match --data-dir
          readinessProbe:
            httpGet:
              path: /health
              port: 2379
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 2379
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: etcd-data
          emptyDir: {}
