/*
 * Copyright (C) 2025 Quasient Inc. <https://www.quasient.com>
 *
 * Use of this software is governed by the Business Source License 1.1
 * included in the file LICENSE and at https://mariadb.com/bsl11
 *
 * Change Date: 2029-10-01
 * Change License: Apache 2.0
 */
package com.quasient.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, meta.colf, primitives.colf, values.colf,
// wrappers.colf and calls.colf.

import static java.lang.String.format;

import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class InstanceFieldGet implements Serializable, com.quasient.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  public Class clazz;

  public String objectRef;

  public Field field;

  public Context context;

  /** Default constructor */
  public InstanceFieldGet() {
    init();
  }

  /** Colfer zero values. */
  private void init() {
    objectRef = "";
  }

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(InstanceFieldGet.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public InstanceFieldGet next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            InstanceFieldGet o = new InstanceFieldGet();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(InstanceFieldGet.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n = 1L + 6 + (long) this.objectRef.length() * 3;
    if (this.clazz != null) n += 1 + (long) this.clazz.marshalFit();
    if (this.field != null) n += 1 + (long) this.field.marshalFit();
    if (this.context != null) n += 1 + (long) this.context.marshalFit();
    if (n < 0 || n > (long) InstanceFieldGet.colferSizeMax) return InstanceFieldGet.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (this.clazz != null) {
        buf[i++] = (byte) 0;
        i = this.clazz.marshal(buf, i);
      }

      if (!this.objectRef.isEmpty()) {
        buf[i++] = (byte) 1;
        int start = ++i;

        String s = this.objectRef;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > InstanceFieldGet.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: com.quasient.pal.messages/colfer.InstanceFieldGet.objectRef size %d exceeds %d UTF-8 bytes",
                  size, InstanceFieldGet.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.field != null) {
        buf[i++] = (byte) 2;
        i = this.field.marshal(buf, i);
      }

      if (this.context != null) {
        buf[i++] = (byte) 3;
        i = this.context.marshal(buf, i);
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > InstanceFieldGet.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: com.quasient.pal.messages/colfer.InstanceFieldGet exceeds %d bytes",
                InstanceFieldGet.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        this.clazz = new Class();
        i = this.clazz.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > InstanceFieldGet.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: com.quasient.pal.messages/colfer.InstanceFieldGet.objectRef size %d exceeds %d UTF-8 bytes",
                  size, InstanceFieldGet.colferSizeMax));

        int start = i;
        i += size;
        this.objectRef = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 2) {
        this.field = new Field();
        i = this.field.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 3) {
        this.context = new Context();
        i = this.context.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < InstanceFieldGet.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > InstanceFieldGet.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: com.quasient.pal.messages/colfer.InstanceFieldGet exceeds %d bytes",
                InstanceFieldGet.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 4L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets com.quasient.pal.messages/colfer.InstanceFieldGet.clazz.
   *
   * @return the value.
   */
  public Class getClazz() {
    return this.clazz;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.clazz.
   *
   * @param value the replacement.
   */
  public void setClazz(Class value) {
    this.clazz = value;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.clazz.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldGet withClazz(Class value) {
    this.clazz = value;
    return this;
  }

  /**
   * Gets com.quasient.pal.messages/colfer.InstanceFieldGet.objectRef.
   *
   * @return the value.
   */
  public String getObjectRef() {
    return this.objectRef;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.objectRef.
   *
   * @param value the replacement.
   */
  public void setObjectRef(String value) {
    this.objectRef = value;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.objectRef.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldGet withObjectRef(String value) {
    this.objectRef = value;
    return this;
  }

  /**
   * Gets com.quasient.pal.messages/colfer.InstanceFieldGet.field.
   *
   * @return the value.
   */
  public Field getField() {
    return this.field;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.field.
   *
   * @param value the replacement.
   */
  public void setField(Field value) {
    this.field = value;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.field.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldGet withField(Field value) {
    this.field = value;
    return this;
  }

  /**
   * Gets com.quasient.pal.messages/colfer.InstanceFieldGet.context.
   *
   * @return the value.
   */
  public Context getContext() {
    return this.context;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.context.
   *
   * @param value the replacement.
   */
  public void setContext(Context value) {
    this.context = value;
  }

  /**
   * Sets com.quasient.pal.messages/colfer.InstanceFieldGet.context.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public InstanceFieldGet withContext(Context value) {
    this.context = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.clazz != null) h = 31 * h + this.clazz.hashCode();
    if (this.objectRef != null) h = 31 * h + this.objectRef.hashCode();
    if (this.field != null) h = 31 * h + this.field.hashCode();
    if (this.context != null) h = 31 * h + this.context.hashCode();
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof InstanceFieldGet && equals((InstanceFieldGet) o);
  }

  public final boolean equals(InstanceFieldGet o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.clazz == null ? o.clazz == null : this.clazz.equals(o.clazz))
        && (this.objectRef == null ? o.objectRef == null : this.objectRef.equals(o.objectRef))
        && (this.field == null ? o.field == null : this.field.equals(o.field))
        && (this.context == null ? o.context == null : this.context.equals(o.context));
  }

  @Override
  public InstanceFieldGet fromJson(JsonObject json) throws JsonParseException {
    try {
      if (json.has("clazz")) {
        JsonObject jsonObj = json.getAsJsonObject("clazz");
        this.clazz = new Class().fromJson(jsonObj);
      }

      if (json.has("objectRef")) {
        this.objectRef = json.get("objectRef").getAsString();
      }

      if (json.has("field")) {
        JsonObject jsonObj = json.getAsJsonObject("field");
        this.field = new Field().fromJson(jsonObj);
      }

      if (json.has("context")) {
        JsonObject jsonObj = json.getAsJsonObject("context");
        this.context = new Context().fromJson(jsonObj);
      }

    } catch (Exception e) {
      throw new JsonParseException("Error deserializing json object: " + e.getMessage(), e);
    }
    return this;
  }
}
