#
# Copyright (C) 2025 Quasient Inc. <https://www.quasient.com>
#
# Use of this software is governed by the Business Source License 1.1
# included in the file LICENSE and at https://mariadb.com/bsl11
#
# Change Date: 2029-10-01
# Change License: Apache 2.0
#

# Context-level ZMQ PROPERTIES
ZMQ_LINGER=1000
ZMQ_RCVHWM=10000
ZMQ_SNDHWM=10000

# KAFKA PROPERTIES
key.serializer=com.quasient.pal.serdes.kafka.KafkaKeySerializer
value.serializer=com.quasient.pal.serdes.kafka.KafkaMessageSerializer
pollDuration=10
enable.auto.commit=false
auto.commit.interval.ms=500
auto.offset.reset=earliest
session.timeout.ms=30000
key.deserializer=com.quasient.pal.serdes.kafka.KafkaKeyDeserializer
value.deserializer=com.quasient.pal.serdes.kafka.KafkaMessageDeserializer

# LOG PROPERTIES
log.threadPoolSize=1

# WAL + PUB QUEUE PROPERTIES (all sizes must be powers of 2)
wal.queue.type = chunked
wal.queue.initial = 16384
wal.queue.max    = 1048576
wal.queue.chunk  = 4096

pub.queue.type = chunked
pub.queue.initial = 16384
pub.queue.max    = 1048576
pub.queue.chunk  = 8192

# MESSAGE PUBLISHER
publisher.spsc_size = 524288
publisher.batch_size = 4096
publisher.flush_on_close = true
publisher.zmq.linger = 0
publisher.zmq.send_timeout = 0
publisher.zmq.send_hwm = 10000
publisher.drop.policy = drop_old
publisher.drop.hwm_pct = 97
publisher.drop.keep_pct = 92
