package net.ittera.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, primitives.colf, values.colf, wrappers.colf and
// calls.colf.

import static java.lang.String.format;

import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class ControlMessage implements Serializable, net.ittera.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  public String fromPeer;

  public String messageUuid;

  public byte command;

  public byte status;

  public String body;

  /** Default constructor */
  public ControlMessage() {
    init();
  }

  /** Colfer zero values. */
  private void init() {
    fromPeer = "";
    messageUuid = "";
    body = "";
  }

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(ControlMessage.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public ControlMessage next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            ControlMessage o = new ControlMessage();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(ControlMessage.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n =
        1L
            + 6
            + (long) this.fromPeer.length() * 3
            + 6
            + (long) this.messageUuid.length() * 3
            + 2
            + 2
            + 6
            + (long) this.body.length() * 3;
    if (n < 0 || n > (long) ControlMessage.colferSizeMax) return ControlMessage.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (!this.fromPeer.isEmpty()) {
        buf[i++] = (byte) 0;
        int start = ++i;

        String s = this.fromPeer;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > ControlMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.ControlMessage.fromPeer size %d exceeds %d UTF-8 bytes",
                  size, ControlMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (!this.messageUuid.isEmpty()) {
        buf[i++] = (byte) 1;
        int start = ++i;

        String s = this.messageUuid;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > ControlMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.ControlMessage.messageUuid size %d exceeds %d UTF-8 bytes",
                  size, ControlMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.command != 0) {
        buf[i++] = (byte) 2;
        buf[i++] = this.command;
      }

      if (this.status != 0) {
        buf[i++] = (byte) 3;
        buf[i++] = this.status;
      }

      if (!this.body.isEmpty()) {
        buf[i++] = (byte) 4;
        int start = ++i;

        String s = this.body;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > ControlMessage.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.ControlMessage.body size %d exceeds %d UTF-8 bytes",
                  size, ControlMessage.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > ControlMessage.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: net.ittera.pal.messages/colfer.ControlMessage exceeds %d bytes",
                ControlMessage.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > ControlMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.ControlMessage.fromPeer size %d exceeds %d UTF-8 bytes",
                  size, ControlMessage.colferSizeMax));

        int start = i;
        i += size;
        this.fromPeer = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > ControlMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.ControlMessage.messageUuid size %d exceeds %d UTF-8 bytes",
                  size, ControlMessage.colferSizeMax));

        int start = i;
        i += size;
        this.messageUuid = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 2) {
        this.command = buf[i++];
        header = buf[i++];
      }

      if (header == (byte) 3) {
        this.status = buf[i++];
        header = buf[i++];
      }

      if (header == (byte) 4) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > ControlMessage.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.ControlMessage.body size %d exceeds %d UTF-8 bytes",
                  size, ControlMessage.colferSizeMax));

        int start = i;
        i += size;
        this.body = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < ControlMessage.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > ControlMessage.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: net.ittera.pal.messages/colfer.ControlMessage exceeds %d bytes",
                ControlMessage.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 5L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ControlMessage.fromPeer.
   *
   * @return the value.
   */
  public String getFromPeer() {
    return this.fromPeer;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.fromPeer.
   *
   * @param value the replacement.
   */
  public void setFromPeer(String value) {
    this.fromPeer = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.fromPeer.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ControlMessage withFromPeer(String value) {
    this.fromPeer = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ControlMessage.messageUuid.
   *
   * @return the value.
   */
  public String getMessageUuid() {
    return this.messageUuid;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.messageUuid.
   *
   * @param value the replacement.
   */
  public void setMessageUuid(String value) {
    this.messageUuid = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.messageUuid.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ControlMessage withMessageUuid(String value) {
    this.messageUuid = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ControlMessage.command.
   *
   * @return the value.
   */
  public byte getCommand() {
    return this.command;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.command.
   *
   * @param value the replacement.
   */
  public void setCommand(byte value) {
    this.command = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.command.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ControlMessage withCommand(byte value) {
    this.command = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ControlMessage.status.
   *
   * @return the value.
   */
  public byte getStatus() {
    return this.status;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.status.
   *
   * @param value the replacement.
   */
  public void setStatus(byte value) {
    this.status = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.status.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ControlMessage withStatus(byte value) {
    this.status = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ControlMessage.body.
   *
   * @return the value.
   */
  public String getBody() {
    return this.body;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.body.
   *
   * @param value the replacement.
   */
  public void setBody(String value) {
    this.body = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ControlMessage.body.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ControlMessage withBody(String value) {
    this.body = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.fromPeer != null) h = 31 * h + this.fromPeer.hashCode();
    if (this.messageUuid != null) h = 31 * h + this.messageUuid.hashCode();
    h = 31 * h + (this.command & 0xff);
    h = 31 * h + (this.status & 0xff);
    if (this.body != null) h = 31 * h + this.body.hashCode();
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof ControlMessage && equals((ControlMessage) o);
  }

  public final boolean equals(ControlMessage o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.fromPeer == null ? o.fromPeer == null : this.fromPeer.equals(o.fromPeer))
        && (this.messageUuid == null
            ? o.messageUuid == null
            : this.messageUuid.equals(o.messageUuid))
        && this.command == o.command
        && this.status == o.status
        && (this.body == null ? o.body == null : this.body.equals(o.body));
  }

  @Override
  public ControlMessage fromJson(JsonObject json) throws JsonParseException {
    try {
      if (json.has("fromPeer")) {
        this.fromPeer = json.get("fromPeer").getAsString();
      }

      if (json.has("messageUuid")) {
        this.messageUuid = json.get("messageUuid").getAsString();
      }

      if (json.has("command")) {
        this.command = json.get("command").getAsByte();
      }

      if (json.has("status")) {
        this.status = json.get("status").getAsByte();
      }

      if (json.has("body")) {
        this.body = json.get("body").getAsString();
      }

    } catch (Exception e) {
      throw new JsonParseException("Error deserializing json object: " + e.getMessage(), e);
    }
    return this;
  }
}
