package net.ittera.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, exceptions.colf, exec.colf, fields.colf,
// headers.colf, intercepts.colf, primitives.colf, values.colf, wrappers.colf and calls.colf.

import static java.lang.String.format;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class RaisedThrowable implements Serializable, net.ittera.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  public Class clazz;

  /** */
  public boolean inInitializer;

  /** */
  public String constructor;

  public String method;

  public String field;

  public int modifiers;

  public Throwable throwable;

  /** Default constructor */
  public RaisedThrowable() {
    init();
  }

  /** Colfer zero values. */
  private void init() {
    constructor = "";
    method = "";
    field = "";
  }

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0)
        buf = new byte[Math.min(RaisedThrowable.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public RaisedThrowable next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            RaisedThrowable o = new RaisedThrowable();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(RaisedThrowable.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n =
        1L
            + 1
            + 6
            + (long) this.constructor.length() * 3
            + 6
            + (long) this.method.length() * 3
            + 6
            + (long) this.field.length() * 3
            + 5;
    if (this.clazz != null) n += 1 + (long) this.clazz.marshalFit();
    if (this.throwable != null) n += 1 + (long) this.throwable.marshalFit();
    if (n < 0 || n > (long) RaisedThrowable.colferSizeMax) return RaisedThrowable.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (this.clazz != null) {
        buf[i++] = (byte) 0;
        i = this.clazz.marshal(buf, i);
      }

      if (this.inInitializer) {
        buf[i++] = (byte) 1;
      }

      if (!this.constructor.isEmpty()) {
        buf[i++] = (byte) 2;
        int start = ++i;

        String s = this.constructor;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > RaisedThrowable.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.RaisedThrowable.constructor size %d exceeds %d UTF-8 bytes",
                  size, RaisedThrowable.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (!this.method.isEmpty()) {
        buf[i++] = (byte) 3;
        int start = ++i;

        String s = this.method;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > RaisedThrowable.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.RaisedThrowable.method size %d exceeds %d UTF-8 bytes",
                  size, RaisedThrowable.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (!this.field.isEmpty()) {
        buf[i++] = (byte) 4;
        int start = ++i;

        String s = this.field;
        for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
          char c = s.charAt(sIndex);
          if (c < '\u0080') {
            buf[i++] = (byte) c;
          } else if (c < '\u0800') {
            buf[i++] = (byte) (192 | c >>> 6);
            buf[i++] = (byte) (128 | c & 63);
          } else if (c < '\ud800' || c > '\udfff') {
            buf[i++] = (byte) (224 | c >>> 12);
            buf[i++] = (byte) (128 | c >>> 6 & 63);
            buf[i++] = (byte) (128 | c & 63);
          } else {
            int cp = 0;
            if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
            if ((cp >= 1 << 16) && (cp < 1 << 21)) {
              buf[i++] = (byte) (240 | cp >>> 18);
              buf[i++] = (byte) (128 | cp >>> 12 & 63);
              buf[i++] = (byte) (128 | cp >>> 6 & 63);
              buf[i++] = (byte) (128 | cp & 63);
            } else buf[i++] = (byte) '?';
          }
        }
        int size = i - start;
        if (size > RaisedThrowable.colferSizeMax)
          throw new IllegalStateException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.RaisedThrowable.field size %d exceeds %d UTF-8 bytes",
                  size, RaisedThrowable.colferSizeMax));

        int ii = start - 1;
        if (size > 0x7f) {
          i++;
          for (int x = size; x >= 1 << 14; x >>>= 7) i++;
          System.arraycopy(buf, start, buf, i - size, size);

          do {
            buf[ii++] = (byte) (size | 0x80);
            size >>>= 7;
          } while (size > 0x7f);
        }
        buf[ii] = (byte) size;
      }

      if (this.modifiers != 0) {
        int x = this.modifiers;
        if ((x & ~((1 << 21) - 1)) != 0) {
          buf[i++] = (byte) (5 | 0x80);
          buf[i++] = (byte) (x >>> 24);
          buf[i++] = (byte) (x >>> 16);
          buf[i++] = (byte) (x >>> 8);
        } else {
          buf[i++] = (byte) 5;
          while (x > 0x7f) {
            buf[i++] = (byte) (x | 0x80);
            x >>>= 7;
          }
        }
        buf[i++] = (byte) x;
      }

      if (this.throwable != null) {
        buf[i++] = (byte) 6;
        i = this.throwable.marshal(buf, i);
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > RaisedThrowable.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: net.ittera.pal.messages/colfer.RaisedThrowable exceeds %d bytes",
                RaisedThrowable.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        this.clazz = new Class();
        i = this.clazz.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 1) {
        this.inInitializer = true;
        header = buf[i++];
      }

      if (header == (byte) 2) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > RaisedThrowable.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.RaisedThrowable.constructor size %d exceeds %d UTF-8 bytes",
                  size, RaisedThrowable.colferSizeMax));

        int start = i;
        i += size;
        this.constructor = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 3) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > RaisedThrowable.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.RaisedThrowable.method size %d exceeds %d UTF-8 bytes",
                  size, RaisedThrowable.colferSizeMax));

        int start = i;
        i += size;
        this.method = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 4) {
        int size = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          size |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        if (size < 0 || size > RaisedThrowable.colferSizeMax)
          throw new SecurityException(
              format(
                  "colfer: net.ittera.pal.messages/colfer.RaisedThrowable.field size %d exceeds %d UTF-8 bytes",
                  size, RaisedThrowable.colferSizeMax));

        int start = i;
        i += size;
        this.field = new String(buf, start, size, StandardCharsets.UTF_8);
        header = buf[i++];
      }

      if (header == (byte) 5) {
        int x = 0;
        for (int shift = 0; true; shift += 7) {
          byte b = buf[i++];
          x |= (b & 0x7f) << shift;
          if (shift == 28 || b >= 0) break;
        }
        this.modifiers = x;
        header = buf[i++];
      } else if (header == (byte) (5 | 0x80)) {
        this.modifiers =
            (buf[i++] & 0xff) << 24
                | (buf[i++] & 0xff) << 16
                | (buf[i++] & 0xff) << 8
                | (buf[i++] & 0xff);
        header = buf[i++];
      }

      if (header == (byte) 6) {
        this.throwable = new Throwable();
        i = this.throwable.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < RaisedThrowable.colferSizeMax)
        throw new BufferUnderflowException();
      if (i < 0 || i - offset > RaisedThrowable.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: net.ittera.pal.messages/colfer.RaisedThrowable exceeds %d bytes",
                RaisedThrowable.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 7L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets net.ittera.pal.messages/colfer.RaisedThrowable.clazz.
   *
   * @return the value.
   */
  public Class getClazz() {
    return this.clazz;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.clazz.
   *
   * @param value the replacement.
   */
  public void setClazz(Class value) {
    this.clazz = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.clazz.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public RaisedThrowable withClazz(Class value) {
    this.clazz = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.RaisedThrowable.inInitializer.
   *
   * @return the value.
   */
  public boolean getInInitializer() {
    return this.inInitializer;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.inInitializer.
   *
   * @param value the replacement.
   */
  public void setInInitializer(boolean value) {
    this.inInitializer = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.inInitializer.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public RaisedThrowable withInInitializer(boolean value) {
    this.inInitializer = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.RaisedThrowable.constructor.
   *
   * @return the value.
   */
  public String getConstructor() {
    return this.constructor;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.constructor.
   *
   * @param value the replacement.
   */
  public void setConstructor(String value) {
    this.constructor = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.constructor.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public RaisedThrowable withConstructor(String value) {
    this.constructor = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.RaisedThrowable.method.
   *
   * @return the value.
   */
  public String getMethod() {
    return this.method;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.method.
   *
   * @param value the replacement.
   */
  public void setMethod(String value) {
    this.method = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.method.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public RaisedThrowable withMethod(String value) {
    this.method = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.RaisedThrowable.field.
   *
   * @return the value.
   */
  public String getField() {
    return this.field;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.field.
   *
   * @param value the replacement.
   */
  public void setField(String value) {
    this.field = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.field.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public RaisedThrowable withField(String value) {
    this.field = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.RaisedThrowable.modifiers.
   *
   * @return the value.
   */
  public int getModifiers() {
    return this.modifiers;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.modifiers.
   *
   * @param value the replacement.
   */
  public void setModifiers(int value) {
    this.modifiers = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.modifiers.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public RaisedThrowable withModifiers(int value) {
    this.modifiers = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.RaisedThrowable.throwable.
   *
   * @return the value.
   */
  public Throwable getThrowable() {
    return this.throwable;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.throwable.
   *
   * @param value the replacement.
   */
  public void setThrowable(Throwable value) {
    this.throwable = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.RaisedThrowable.throwable.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public RaisedThrowable withThrowable(Throwable value) {
    this.throwable = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    if (this.clazz != null) h = 31 * h + this.clazz.hashCode();
    h = 31 * h + (this.inInitializer ? 1231 : 1237);
    if (this.constructor != null) h = 31 * h + this.constructor.hashCode();
    if (this.method != null) h = 31 * h + this.method.hashCode();
    if (this.field != null) h = 31 * h + this.field.hashCode();
    h = 31 * h + this.modifiers;
    if (this.throwable != null) h = 31 * h + this.throwable.hashCode();
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof RaisedThrowable && equals((RaisedThrowable) o);
  }

  public final boolean equals(RaisedThrowable o) {
    if (o == null) return false;
    if (o == this) return true;

    return (this.clazz == null ? o.clazz == null : this.clazz.equals(o.clazz))
        && this.inInitializer == o.inInitializer
        && (this.constructor == null
            ? o.constructor == null
            : this.constructor.equals(o.constructor))
        && (this.method == null ? o.method == null : this.method.equals(o.method))
        && (this.field == null ? o.field == null : this.field.equals(o.field))
        && this.modifiers == o.modifiers
        && (this.throwable == null ? o.throwable == null : this.throwable.equals(o.throwable));
  }
}
