package net.ittera.pal.messages.colfer;

// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file context.colf, control.colf, exceptions.colf, exec.colf,
// fields.colf, headers.colf, intercepts.colf, primitives.colf, values.colf, wrappers.colf and
// calls.colf.

import static java.lang.String.format;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamException;
import java.io.OutputStream;
import java.io.Serializable;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.util.InputMismatchException;

/**
 * Data bean with built-in serialization support.
 *
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class ReturnValue implements Serializable, net.ittera.pal.messages.Marshallable {

  /** The upper limit for serial byte sizes. */
  public static int colferSizeMax = 16 * 1024 * 1024;

  public boolean isVoid;

  public boolean isClass;

  public Obj object;

  /** the method/constructor returning this object */
  public Reflectable from;

  /**
   * the class returning this object through a fieldop, constructor or method (i.e. the declaring
   * class)
   */
  public Class clazz;

  /** Default constructor */
  public ReturnValue() {
    init();
  }

  /** Colfer zero values. */
  private void init() {}

  /** {@link #reset(InputStream) Reusable} deserialization of Colfer streams. */
  public static class Unmarshaller {

    /** The data source. */
    protected InputStream in;

    /** The read buffer. */
    public byte[] buf;

    /** The {@link #buf buffer}'s data start index, inclusive. */
    protected int offset;

    /** The {@link #buf buffer}'s data end index, exclusive. */
    protected int i;

    /**
     * @param in the data source or {@code null}.
     * @param buf the initial buffer or {@code null}.
     */
    public Unmarshaller(InputStream in, byte[] buf) {
      if (buf == null || buf.length == 0) buf = new byte[Math.min(ReturnValue.colferSizeMax, 2048)];
      this.buf = buf;
      reset(in);
    }

    /**
     * Reuses the marshaller.
     *
     * @param in the data source or {@code null}.
     * @throws IllegalStateException on pending data.
     */
    public void reset(InputStream in) {
      if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
      this.in = in;
      this.offset = 0;
      this.i = 0;
    }

    /**
     * Deserializes the following object.
     *
     * @return the result or {@code null} when EOF.
     * @throws IOException from the input stream.
     * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
     * @throws InputMismatchException when the data does not match this object's schema.
     */
    public ReturnValue next() throws IOException {
      if (in == null) return null;

      while (true) {
        if (this.i > this.offset) {
          try {
            ReturnValue o = new ReturnValue();
            this.offset = o.unmarshal(this.buf, this.offset, this.i);
            return o;
          } catch (BufferUnderflowException e) {
          }
        }
        // not enough data

        if (this.i <= this.offset) {
          this.offset = 0;
          this.i = 0;
        } else if (i == buf.length) {
          byte[] src = this.buf;
          if (offset == 0)
            this.buf = new byte[Math.min(ReturnValue.colferSizeMax, this.buf.length * 4)];
          System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
          this.i -= this.offset;
          this.offset = 0;
        }
        assert this.i < this.buf.length;

        int n = in.read(buf, i, buf.length - i);
        if (n < 0) {
          if (this.i > this.offset)
            throw new InputMismatchException("colfer: pending data with EOF");
          return null;
        }
        assert n > 0;
        i += n;
      }
    }
  }

  /**
   * Gets the serial size estimate as an upper boundary, whereby {@link #marshal(byte[],int)} ≤
   * {@link #marshalFit()} ≤ {@link #colferSizeMax}.
   *
   * @return the number of bytes.
   */
  public int marshalFit() {
    long n = 1L + 1 + 1;
    if (this.object != null) n += 1 + (long) this.object.marshalFit();
    if (this.from != null) n += 1 + (long) this.from.marshalFit();
    if (this.clazz != null) n += 1 + (long) this.clazz.marshalFit();
    if (n < 0 || n > (long) ReturnValue.colferSizeMax) return ReturnValue.colferSizeMax;
    return (int) n;
  }

  /**
   * Serializes the object.
   *
   * @param out the data destination.
   * @param buf the initial buffer or {@code null}.
   * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
   *     Otherwise the return is a new buffer, large enough to hold the whole serial.
   * @throws IOException from {@code out}.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
    int n = 0;
    if (buf != null && buf.length != 0)
      try {
        n = marshal(buf, 0);
      } catch (BufferOverflowException e) {
      }
    if (n == 0) {
      buf = new byte[marshalFit()];
      n = marshal(buf, 0);
    }
    out.write(buf, 0, n);
    return buf;
  }

  /**
   * Serializes the object.
   *
   * @param buf the data destination.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferOverflowException when {@code buf} is too small.
   * @throws IllegalStateException on an upper limit breach defined by {@link #colferSizeMax}.
   */
  public int marshal(byte[] buf, int offset) {
    int i = offset;

    try {
      if (this.isVoid) {
        buf[i++] = (byte) 0;
      }

      if (this.isClass) {
        buf[i++] = (byte) 1;
      }

      if (this.object != null) {
        buf[i++] = (byte) 2;
        i = this.object.marshal(buf, i);
      }

      if (this.from != null) {
        buf[i++] = (byte) 3;
        i = this.from.marshal(buf, i);
      }

      if (this.clazz != null) {
        buf[i++] = (byte) 4;
        i = this.clazz.marshal(buf, i);
      }

      buf[i++] = (byte) 0x7f;
      return i;
    } catch (ArrayIndexOutOfBoundsException e) {
      if (i - offset > ReturnValue.colferSizeMax)
        throw new IllegalStateException(
            format(
                "colfer: net.ittera.pal.messages/colfer.ReturnValue exceeds %d bytes",
                ReturnValue.colferSizeMax));
      if (i > buf.length) throw new BufferOverflowException();
      throw e;
    }
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset) {
    return unmarshal(buf, offset, buf.length);
  }

  /**
   * Deserializes the object.
   *
   * @param buf the data source.
   * @param offset the initial index for {@code buf}, inclusive.
   * @param end the index limit for {@code buf}, exclusive.
   * @return the final index for {@code buf}, exclusive.
   * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
   * @throws SecurityException on an upper limit breach defined by {@link #colferSizeMax}.
   * @throws InputMismatchException when the data does not match this object's schema.
   */
  public int unmarshal(byte[] buf, int offset, int end) {
    if (end > buf.length) end = buf.length;
    int i = offset;

    try {
      byte header = buf[i++];

      if (header == (byte) 0) {
        this.isVoid = true;
        header = buf[i++];
      }

      if (header == (byte) 1) {
        this.isClass = true;
        header = buf[i++];
      }

      if (header == (byte) 2) {
        this.object = new Obj();
        i = this.object.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 3) {
        this.from = new Reflectable();
        i = this.from.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header == (byte) 4) {
        this.clazz = new Class();
        i = this.clazz.unmarshal(buf, i, end);
        header = buf[i++];
      }

      if (header != (byte) 0x7f)
        throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
    } finally {
      if (i > end && end - offset < ReturnValue.colferSizeMax) throw new BufferUnderflowException();
      if (i < 0 || i - offset > ReturnValue.colferSizeMax)
        throw new SecurityException(
            format(
                "colfer: net.ittera.pal.messages/colfer.ReturnValue exceeds %d bytes",
                ReturnValue.colferSizeMax));
      if (i > end) throw new BufferUnderflowException();
    }

    return i;
  }

  // {@link Serializable} version number.
  private static final long serialVersionUID = 5L;

  // {@link Serializable} Colfer extension.
  private void writeObject(ObjectOutputStream out) throws IOException {
    byte[] buf = new byte[marshalFit()];
    int n = marshal(buf, 0);
    out.writeInt(n);
    out.write(buf, 0, n);
  }

  // {@link Serializable} Colfer extension.
  private void readObject(ObjectInputStream in) throws ClassNotFoundException, IOException {
    init();

    int n = in.readInt();
    byte[] buf = new byte[n];
    in.readFully(buf);
    unmarshal(buf, 0);
  }

  // {@link Serializable} Colfer extension.
  private void readObjectNoData() throws ObjectStreamException {
    init();
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ReturnValue.isVoid.
   *
   * @return the value.
   */
  public boolean getIsVoid() {
    return this.isVoid;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.isVoid.
   *
   * @param value the replacement.
   */
  public void setIsVoid(boolean value) {
    this.isVoid = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.isVoid.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ReturnValue withIsVoid(boolean value) {
    this.isVoid = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ReturnValue.isClass.
   *
   * @return the value.
   */
  public boolean getIsClass() {
    return this.isClass;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.isClass.
   *
   * @param value the replacement.
   */
  public void setIsClass(boolean value) {
    this.isClass = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.isClass.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ReturnValue withIsClass(boolean value) {
    this.isClass = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ReturnValue.object.
   *
   * @return the value.
   */
  public Obj getObject() {
    return this.object;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.object.
   *
   * @param value the replacement.
   */
  public void setObject(Obj value) {
    this.object = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.object.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ReturnValue withObject(Obj value) {
    this.object = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ReturnValue.from.
   *
   * @return the value.
   */
  public Reflectable getFrom() {
    return this.from;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.from.
   *
   * @param value the replacement.
   */
  public void setFrom(Reflectable value) {
    this.from = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.from.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ReturnValue withFrom(Reflectable value) {
    this.from = value;
    return this;
  }

  /**
   * Gets net.ittera.pal.messages/colfer.ReturnValue.clazz.
   *
   * @return the value.
   */
  public Class getClazz() {
    return this.clazz;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.clazz.
   *
   * @param value the replacement.
   */
  public void setClazz(Class value) {
    this.clazz = value;
  }

  /**
   * Sets net.ittera.pal.messages/colfer.ReturnValue.clazz.
   *
   * @param value the replacement.
   * @return {@code this}.
   */
  public ReturnValue withClazz(Class value) {
    this.clazz = value;
    return this;
  }

  @Override
  public final int hashCode() {
    int h = 1;
    h = 31 * h + (this.isVoid ? 1231 : 1237);
    h = 31 * h + (this.isClass ? 1231 : 1237);
    if (this.object != null) h = 31 * h + this.object.hashCode();
    if (this.from != null) h = 31 * h + this.from.hashCode();
    if (this.clazz != null) h = 31 * h + this.clazz.hashCode();
    return h;
  }

  @Override
  public final boolean equals(Object o) {
    return o instanceof ReturnValue && equals((ReturnValue) o);
  }

  public final boolean equals(ReturnValue o) {
    if (o == null) return false;
    if (o == this) return true;

    return this.isVoid == o.isVoid
        && this.isClass == o.isClass
        && (this.object == null ? o.object == null : this.object.equals(o.object))
        && (this.from == null ? o.from == null : this.from.equals(o.from))
        && (this.clazz == null ? o.clazz == null : this.clazz.equals(o.clazz));
  }
}
