version: '3.6'


networks:
  peernet:
    driver: bridge
    name: peers

services:

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      JMX_PORT: 10122
    networks:
      - peernet
    ports:
      - "2181:2181"
      - "10122:10122"

  kafka:
    image: wurstmeister/kafka:1.1.0
    networks:
      - peernet
    ports:
      - "9092:9092"
      - "9094:9094"
      - "10121:10121"
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /data/kafka-logs
      JMX_PORT: 10121
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka-logs/docker:/data/kafka-logs
